// Code generated by volcengine with private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package vmpiface provides an interface to enable mocking the VMP service client
// for testing your code.
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters.
package vmp

import (
	"github.com/volcengine/volcengine-go-sdk/volcengine"
	"github.com/volcengine/volcengine-go-sdk/volcengine/request"
)

// VMPAPI provides an interface to enable mocking the
// vmp.VMP service client's API operation,
//
//    // volcengine sdk func uses an SDK service client to make a request to
//    // VMP.
//    func myFunc(svc VMPAPI) bool {
//        // Make svc.CreateWorkspace request
//    }
//
//    func main() {
//        sess := session.New()
//        svc := vmp.New(sess)
//
//        myFunc(svc)
//    }
//
type VMPAPI interface {
	CreateWorkspaceCommon(*map[string]interface{}) (*map[string]interface{}, error)
	CreateWorkspaceCommonWithContext(volcengine.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateWorkspaceCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateWorkspace(*CreateWorkspaceInput) (*CreateWorkspaceOutput, error)
	CreateWorkspaceWithContext(volcengine.Context, *CreateWorkspaceInput, ...request.Option) (*CreateWorkspaceOutput, error)
	CreateWorkspaceRequest(*CreateWorkspaceInput) (*request.Request, *CreateWorkspaceOutput)

	DeleteWorkspaceCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteWorkspaceCommonWithContext(volcengine.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteWorkspaceCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteWorkspace(*DeleteWorkspaceInput) (*DeleteWorkspaceOutput, error)
	DeleteWorkspaceWithContext(volcengine.Context, *DeleteWorkspaceInput, ...request.Option) (*DeleteWorkspaceOutput, error)
	DeleteWorkspaceRequest(*DeleteWorkspaceInput) (*request.Request, *DeleteWorkspaceOutput)

	ListWorkspaceStatusCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ListWorkspaceStatusCommonWithContext(volcengine.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListWorkspaceStatusCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListWorkspaceStatus(*ListWorkspaceStatusInput) (*ListWorkspaceStatusOutput, error)
	ListWorkspaceStatusWithContext(volcengine.Context, *ListWorkspaceStatusInput, ...request.Option) (*ListWorkspaceStatusOutput, error)
	ListWorkspaceStatusRequest(*ListWorkspaceStatusInput) (*request.Request, *ListWorkspaceStatusOutput)

	ListWorkspacesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ListWorkspacesCommonWithContext(volcengine.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListWorkspacesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListWorkspaces(*ListWorkspacesInput) (*ListWorkspacesOutput, error)
	ListWorkspacesWithContext(volcengine.Context, *ListWorkspacesInput, ...request.Option) (*ListWorkspacesOutput, error)
	ListWorkspacesRequest(*ListWorkspacesInput) (*request.Request, *ListWorkspacesOutput)

	UpdateWorkspaceCommon(*map[string]interface{}) (*map[string]interface{}, error)
	UpdateWorkspaceCommonWithContext(volcengine.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	UpdateWorkspaceCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	UpdateWorkspace(*UpdateWorkspaceInput) (*UpdateWorkspaceOutput, error)
	UpdateWorkspaceWithContext(volcengine.Context, *UpdateWorkspaceInput, ...request.Option) (*UpdateWorkspaceOutput, error)
	UpdateWorkspaceRequest(*UpdateWorkspaceInput) (*request.Request, *UpdateWorkspaceOutput)
}

var _ VMPAPI = (*VMP)(nil)
