// Code generated by volcstack with private/model/cli/gen-api/main.go. DO NOT EDIT.

package clb

import (
	"github.com/volcengine/volcstack-go-sdk/volcstack"
	"github.com/volcengine/volcstack-go-sdk/volcstack/request"
	"github.com/volcengine/volcstack-go-sdk/volcstack/response"
	"github.com/volcengine/volcstack-go-sdk/volcstack/volcstackutil"
)

const opDeleteRulesCommon = "DeleteRules"

// DeleteRulesCommonRequest generates a "volcstack/request.Request" representing the
// client's request for the DeleteRulesCommon operation. The "output" return
// value will be populated with the DeleteRulesCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned DeleteRulesCommon Request to send the API call to the service.
// the "output" return value is not valid until after DeleteRulesCommon Send returns without error.
//
// See DeleteRulesCommon for more information on using the DeleteRulesCommon
// API call, and error handling.
//
//    // Example sending a request using the DeleteRulesCommonRequest method.
//    req, resp := client.DeleteRulesCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *CLB) DeleteRulesCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opDeleteRulesCommon,
		HTTPMethod: "GET",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	return
}

// DeleteRulesCommon API operation for CLB.
//
// Returns volcstackerr.Error for service API and SDK errors. Use runtime type assertions
// with volcstackerr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the VOLCSTACK API reference guide for CLB's
// API operation DeleteRulesCommon for usage and error information.
func (c *CLB) DeleteRulesCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.DeleteRulesCommonRequest(input)
	return out, req.Send()
}

// DeleteRulesCommonWithContext is the same as DeleteRulesCommon with the addition of
// the ability to pass a context and additional request options.
//
// See DeleteRulesCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *CLB) DeleteRulesCommonWithContext(ctx volcstack.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.DeleteRulesCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opDeleteRules = "DeleteRules"

// DeleteRulesRequest generates a "volcstack/request.Request" representing the
// client's request for the DeleteRules operation. The "output" return
// value will be populated with the DeleteRulesCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned DeleteRulesCommon Request to send the API call to the service.
// the "output" return value is not valid until after DeleteRulesCommon Send returns without error.
//
// See DeleteRules for more information on using the DeleteRules
// API call, and error handling.
//
//    // Example sending a request using the DeleteRulesRequest method.
//    req, resp := client.DeleteRulesRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *CLB) DeleteRulesRequest(input *DeleteRulesInput) (req *request.Request, output *DeleteRulesOutput) {
	op := &request.Operation{
		Name:       opDeleteRules,
		HTTPMethod: "GET",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &DeleteRulesInput{}
	}

	output = &DeleteRulesOutput{}
	req = c.newRequest(op, input, output)

	return
}

// DeleteRules API operation for CLB.
//
// Returns volcstackerr.Error for service API and SDK errors. Use runtime type assertions
// with volcstackerr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the VOLCSTACK API reference guide for CLB's
// API operation DeleteRules for usage and error information.
func (c *CLB) DeleteRules(input *DeleteRulesInput) (*DeleteRulesOutput, error) {
	req, out := c.DeleteRulesRequest(input)
	return out, req.Send()
}

// DeleteRulesWithContext is the same as DeleteRules with the addition of
// the ability to pass a context and additional request options.
//
// See DeleteRules for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *CLB) DeleteRulesWithContext(ctx volcstack.Context, input *DeleteRulesInput, opts ...request.Option) (*DeleteRulesOutput, error) {
	req, out := c.DeleteRulesRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type DeleteRulesInput struct {
	_ struct{} `type:"structure"`

	// ListenerId is a required field
	ListenerId *string `type:"string" required:"true"`

	// RuleIds is a required field
	RuleIds []*string `type:"list" required:"true"`
}

// String returns the string representation
func (s DeleteRulesInput) String() string {
	return volcstackutil.Prettify(s)
}

// GoString returns the string representation
func (s DeleteRulesInput) GoString() string {
	return s.String()
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *DeleteRulesInput) Validate() error {
	invalidParams := request.ErrInvalidParams{Context: "DeleteRulesInput"}
	if s.ListenerId == nil {
		invalidParams.Add(request.NewErrParamRequired("ListenerId"))
	}
	if s.RuleIds == nil {
		invalidParams.Add(request.NewErrParamRequired("RuleIds"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

// SetListenerId sets the ListenerId field's value.
func (s *DeleteRulesInput) SetListenerId(v string) *DeleteRulesInput {
	s.ListenerId = &v
	return s
}

// SetRuleIds sets the RuleIds field's value.
func (s *DeleteRulesInput) SetRuleIds(v []*string) *DeleteRulesInput {
	s.RuleIds = v
	return s
}

type DeleteRulesOutput struct {
	_ struct{} `type:"structure"`

	Metadata *response.ResponseMetadata

	RequestId *string `type:"string"`
}

// String returns the string representation
func (s DeleteRulesOutput) String() string {
	return volcstackutil.Prettify(s)
}

// GoString returns the string representation
func (s DeleteRulesOutput) GoString() string {
	return s.String()
}

// SetRequestId sets the RequestId field's value.
func (s *DeleteRulesOutput) SetRequestId(v string) *DeleteRulesOutput {
	s.RequestId = &v
	return s
}
