// Code generated by volcengine with private/model/cli/gen-api/main.go. DO NOT EDIT.

package id

import (
	"github.com/volcengine/volcengine-go-sdk/volcengine"
	"github.com/volcengine/volcengine-go-sdk/volcengine/request"
	"github.com/volcengine/volcengine-go-sdk/volcengine/response"
	"github.com/volcengine/volcengine-go-sdk/volcengine/volcengineutil"
)

const opListSharedOauth2CredentialsCommon = "ListSharedOauth2Credentials"

// ListSharedOauth2CredentialsCommonRequest generates a "volcengine/request.Request" representing the
// client's request for the ListSharedOauth2CredentialsCommon operation. The "output" return
// value will be populated with the ListSharedOauth2CredentialsCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned ListSharedOauth2CredentialsCommon Request to send the API call to the service.
// the "output" return value is not valid until after ListSharedOauth2CredentialsCommon Send returns without error.
//
// See ListSharedOauth2CredentialsCommon for more information on using the ListSharedOauth2CredentialsCommon
// API call, and error handling.
//
//    // Example sending a request using the ListSharedOauth2CredentialsCommonRequest method.
//    req, resp := client.ListSharedOauth2CredentialsCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *ID) ListSharedOauth2CredentialsCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opListSharedOauth2CredentialsCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// ListSharedOauth2CredentialsCommon API operation for ID.
//
// Returns volcengineerr.Error for service API and SDK errors. Use runtime type assertions
// with volcengineerr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the VOLCENGINE API reference guide for ID's
// API operation ListSharedOauth2CredentialsCommon for usage and error information.
func (c *ID) ListSharedOauth2CredentialsCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.ListSharedOauth2CredentialsCommonRequest(input)
	return out, req.Send()
}

// ListSharedOauth2CredentialsCommonWithContext is the same as ListSharedOauth2CredentialsCommon with the addition of
// the ability to pass a context and additional request options.
//
// See ListSharedOauth2CredentialsCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *ID) ListSharedOauth2CredentialsCommonWithContext(ctx volcengine.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.ListSharedOauth2CredentialsCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opListSharedOauth2Credentials = "ListSharedOauth2Credentials"

// ListSharedOauth2CredentialsRequest generates a "volcengine/request.Request" representing the
// client's request for the ListSharedOauth2Credentials operation. The "output" return
// value will be populated with the ListSharedOauth2CredentialsCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned ListSharedOauth2CredentialsCommon Request to send the API call to the service.
// the "output" return value is not valid until after ListSharedOauth2CredentialsCommon Send returns without error.
//
// See ListSharedOauth2Credentials for more information on using the ListSharedOauth2Credentials
// API call, and error handling.
//
//    // Example sending a request using the ListSharedOauth2CredentialsRequest method.
//    req, resp := client.ListSharedOauth2CredentialsRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *ID) ListSharedOauth2CredentialsRequest(input *ListSharedOauth2CredentialsInput) (req *request.Request, output *ListSharedOauth2CredentialsOutput) {
	op := &request.Operation{
		Name:       opListSharedOauth2Credentials,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &ListSharedOauth2CredentialsInput{}
	}

	output = &ListSharedOauth2CredentialsOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// ListSharedOauth2Credentials API operation for ID.
//
// Returns volcengineerr.Error for service API and SDK errors. Use runtime type assertions
// with volcengineerr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the VOLCENGINE API reference guide for ID's
// API operation ListSharedOauth2Credentials for usage and error information.
func (c *ID) ListSharedOauth2Credentials(input *ListSharedOauth2CredentialsInput) (*ListSharedOauth2CredentialsOutput, error) {
	req, out := c.ListSharedOauth2CredentialsRequest(input)
	return out, req.Send()
}

// ListSharedOauth2CredentialsWithContext is the same as ListSharedOauth2Credentials with the addition of
// the ability to pass a context and additional request options.
//
// See ListSharedOauth2Credentials for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *ID) ListSharedOauth2CredentialsWithContext(ctx volcengine.Context, input *ListSharedOauth2CredentialsInput, opts ...request.Option) (*ListSharedOauth2CredentialsOutput, error) {
	req, out := c.ListSharedOauth2CredentialsRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type FilterForListSharedOauth2CredentialsInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Name *string `type:"string" json:",omitempty"`

	PoolName *string `type:"string" json:",omitempty"`

	ProviderName *string `type:"string" json:",omitempty"`

	Source *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s FilterForListSharedOauth2CredentialsInput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s FilterForListSharedOauth2CredentialsInput) GoString() string {
	return s.String()
}

// SetName sets the Name field's value.
func (s *FilterForListSharedOauth2CredentialsInput) SetName(v string) *FilterForListSharedOauth2CredentialsInput {
	s.Name = &v
	return s
}

// SetPoolName sets the PoolName field's value.
func (s *FilterForListSharedOauth2CredentialsInput) SetPoolName(v string) *FilterForListSharedOauth2CredentialsInput {
	s.PoolName = &v
	return s
}

// SetProviderName sets the ProviderName field's value.
func (s *FilterForListSharedOauth2CredentialsInput) SetProviderName(v string) *FilterForListSharedOauth2CredentialsInput {
	s.ProviderName = &v
	return s
}

// SetSource sets the Source field's value.
func (s *FilterForListSharedOauth2CredentialsInput) SetSource(v string) *FilterForListSharedOauth2CredentialsInput {
	s.Source = &v
	return s
}

type ListSharedOauth2CredentialsInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Filter *FilterForListSharedOauth2CredentialsInput `type:"structure" json:",omitempty"`

	// PageNumber is a required field
	PageNumber *int32 `type:"int32" json:",omitempty" required:"true"`

	// PageSize is a required field
	PageSize *int32 `type:"int32" json:",omitempty" required:"true"`

	SortDesc *bool `type:"boolean" json:",omitempty"`

	SortField *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s ListSharedOauth2CredentialsInput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s ListSharedOauth2CredentialsInput) GoString() string {
	return s.String()
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *ListSharedOauth2CredentialsInput) Validate() error {
	invalidParams := request.ErrInvalidParams{Context: "ListSharedOauth2CredentialsInput"}
	if s.PageNumber == nil {
		invalidParams.Add(request.NewErrParamRequired("PageNumber"))
	}
	if s.PageSize == nil {
		invalidParams.Add(request.NewErrParamRequired("PageSize"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

// SetFilter sets the Filter field's value.
func (s *ListSharedOauth2CredentialsInput) SetFilter(v *FilterForListSharedOauth2CredentialsInput) *ListSharedOauth2CredentialsInput {
	s.Filter = v
	return s
}

// SetPageNumber sets the PageNumber field's value.
func (s *ListSharedOauth2CredentialsInput) SetPageNumber(v int32) *ListSharedOauth2CredentialsInput {
	s.PageNumber = &v
	return s
}

// SetPageSize sets the PageSize field's value.
func (s *ListSharedOauth2CredentialsInput) SetPageSize(v int32) *ListSharedOauth2CredentialsInput {
	s.PageSize = &v
	return s
}

// SetSortDesc sets the SortDesc field's value.
func (s *ListSharedOauth2CredentialsInput) SetSortDesc(v bool) *ListSharedOauth2CredentialsInput {
	s.SortDesc = &v
	return s
}

// SetSortField sets the SortField field's value.
func (s *ListSharedOauth2CredentialsInput) SetSortField(v string) *ListSharedOauth2CredentialsInput {
	s.SortField = &v
	return s
}

type ListSharedOauth2CredentialsOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata

	PageNumber *int32 `type:"int32" json:",omitempty"`

	PageSize *int32 `type:"int32" json:",omitempty"`

	SharedOauth2Credentials []*SharedOauth2CredentialForListSharedOauth2CredentialsOutput `type:"list"`

	TotalCount *int32 `type:"int32" json:",omitempty"`
}

// String returns the string representation
func (s ListSharedOauth2CredentialsOutput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s ListSharedOauth2CredentialsOutput) GoString() string {
	return s.String()
}

// SetPageNumber sets the PageNumber field's value.
func (s *ListSharedOauth2CredentialsOutput) SetPageNumber(v int32) *ListSharedOauth2CredentialsOutput {
	s.PageNumber = &v
	return s
}

// SetPageSize sets the PageSize field's value.
func (s *ListSharedOauth2CredentialsOutput) SetPageSize(v int32) *ListSharedOauth2CredentialsOutput {
	s.PageSize = &v
	return s
}

// SetSharedOauth2Credentials sets the SharedOauth2Credentials field's value.
func (s *ListSharedOauth2CredentialsOutput) SetSharedOauth2Credentials(v []*SharedOauth2CredentialForListSharedOauth2CredentialsOutput) *ListSharedOauth2CredentialsOutput {
	s.SharedOauth2Credentials = v
	return s
}

// SetTotalCount sets the TotalCount field's value.
func (s *ListSharedOauth2CredentialsOutput) SetTotalCount(v int32) *ListSharedOauth2CredentialsOutput {
	s.TotalCount = &v
	return s
}

type SharedOauth2CredentialForListSharedOauth2CredentialsOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	CreatedAt *string `type:"string" json:",omitempty"`

	Name *string `type:"string" json:",omitempty"`

	ProviderName *string `type:"string" json:",omitempty"`

	Source *string `type:"string" json:",omitempty"`

	UpdatedAt *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s SharedOauth2CredentialForListSharedOauth2CredentialsOutput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s SharedOauth2CredentialForListSharedOauth2CredentialsOutput) GoString() string {
	return s.String()
}

// SetCreatedAt sets the CreatedAt field's value.
func (s *SharedOauth2CredentialForListSharedOauth2CredentialsOutput) SetCreatedAt(v string) *SharedOauth2CredentialForListSharedOauth2CredentialsOutput {
	s.CreatedAt = &v
	return s
}

// SetName sets the Name field's value.
func (s *SharedOauth2CredentialForListSharedOauth2CredentialsOutput) SetName(v string) *SharedOauth2CredentialForListSharedOauth2CredentialsOutput {
	s.Name = &v
	return s
}

// SetProviderName sets the ProviderName field's value.
func (s *SharedOauth2CredentialForListSharedOauth2CredentialsOutput) SetProviderName(v string) *SharedOauth2CredentialForListSharedOauth2CredentialsOutput {
	s.ProviderName = &v
	return s
}

// SetSource sets the Source field's value.
func (s *SharedOauth2CredentialForListSharedOauth2CredentialsOutput) SetSource(v string) *SharedOauth2CredentialForListSharedOauth2CredentialsOutput {
	s.Source = &v
	return s
}

// SetUpdatedAt sets the UpdatedAt field's value.
func (s *SharedOauth2CredentialForListSharedOauth2CredentialsOutput) SetUpdatedAt(v string) *SharedOauth2CredentialForListSharedOauth2CredentialsOutput {
	s.UpdatedAt = &v
	return s
}
