// Code generated by volcengine with private/model/cli/gen-api/main.go. DO NOT EDIT.

package id

import (
	"github.com/volcengine/volcengine-go-sdk/volcengine"
	"github.com/volcengine/volcengine-go-sdk/volcengine/request"
	"github.com/volcengine/volcengine-go-sdk/volcengine/response"
	"github.com/volcengine/volcengine-go-sdk/volcengine/volcengineutil"
)

const opCreateRouteCommon = "CreateRoute"

// CreateRouteCommonRequest generates a "volcengine/request.Request" representing the
// client's request for the CreateRouteCommon operation. The "output" return
// value will be populated with the CreateRouteCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned CreateRouteCommon Request to send the API call to the service.
// the "output" return value is not valid until after CreateRouteCommon Send returns without error.
//
// See CreateRouteCommon for more information on using the CreateRouteCommon
// API call, and error handling.
//
//    // Example sending a request using the CreateRouteCommonRequest method.
//    req, resp := client.CreateRouteCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *ID) CreateRouteCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opCreateRouteCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// CreateRouteCommon API operation for ID.
//
// Returns volcengineerr.Error for service API and SDK errors. Use runtime type assertions
// with volcengineerr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the VOLCENGINE API reference guide for ID's
// API operation CreateRouteCommon for usage and error information.
func (c *ID) CreateRouteCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.CreateRouteCommonRequest(input)
	return out, req.Send()
}

// CreateRouteCommonWithContext is the same as CreateRouteCommon with the addition of
// the ability to pass a context and additional request options.
//
// See CreateRouteCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *ID) CreateRouteCommonWithContext(ctx volcengine.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.CreateRouteCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opCreateRoute = "CreateRoute"

// CreateRouteRequest generates a "volcengine/request.Request" representing the
// client's request for the CreateRoute operation. The "output" return
// value will be populated with the CreateRouteCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned CreateRouteCommon Request to send the API call to the service.
// the "output" return value is not valid until after CreateRouteCommon Send returns without error.
//
// See CreateRoute for more information on using the CreateRoute
// API call, and error handling.
//
//    // Example sending a request using the CreateRouteRequest method.
//    req, resp := client.CreateRouteRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *ID) CreateRouteRequest(input *CreateRouteInput) (req *request.Request, output *CreateRouteOutput) {
	op := &request.Operation{
		Name:       opCreateRoute,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &CreateRouteInput{}
	}

	output = &CreateRouteOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// CreateRoute API operation for ID.
//
// Returns volcengineerr.Error for service API and SDK errors. Use runtime type assertions
// with volcengineerr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the VOLCENGINE API reference guide for ID's
// API operation CreateRoute for usage and error information.
func (c *ID) CreateRoute(input *CreateRouteInput) (*CreateRouteOutput, error) {
	req, out := c.CreateRouteRequest(input)
	return out, req.Send()
}

// CreateRouteWithContext is the same as CreateRoute with the addition of
// the ability to pass a context and additional request options.
//
// See CreateRoute for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *ID) CreateRouteWithContext(ctx volcengine.Context, input *CreateRouteInput, opts ...request.Option) (*CreateRouteOutput, error) {
	req, out := c.CreateRouteRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type ApiSpecForCreateRouteInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	ActionType *string `type:"string" json:",omitempty"`

	ActionValue *string `type:"string" json:",omitempty"`

	Extractors []*ExtractorForCreateRouteInput `type:"list" json:",omitempty"`

	IdentifierType *int32 `type:"int32" json:",omitempty"`

	IdentifierValue *string `type:"string" json:",omitempty"`

	ResponseFilters []*ResponseFilterForCreateRouteInput `type:"list" json:",omitempty"`
}

// String returns the string representation
func (s ApiSpecForCreateRouteInput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s ApiSpecForCreateRouteInput) GoString() string {
	return s.String()
}

// SetActionType sets the ActionType field's value.
func (s *ApiSpecForCreateRouteInput) SetActionType(v string) *ApiSpecForCreateRouteInput {
	s.ActionType = &v
	return s
}

// SetActionValue sets the ActionValue field's value.
func (s *ApiSpecForCreateRouteInput) SetActionValue(v string) *ApiSpecForCreateRouteInput {
	s.ActionValue = &v
	return s
}

// SetExtractors sets the Extractors field's value.
func (s *ApiSpecForCreateRouteInput) SetExtractors(v []*ExtractorForCreateRouteInput) *ApiSpecForCreateRouteInput {
	s.Extractors = v
	return s
}

// SetIdentifierType sets the IdentifierType field's value.
func (s *ApiSpecForCreateRouteInput) SetIdentifierType(v int32) *ApiSpecForCreateRouteInput {
	s.IdentifierType = &v
	return s
}

// SetIdentifierValue sets the IdentifierValue field's value.
func (s *ApiSpecForCreateRouteInput) SetIdentifierValue(v string) *ApiSpecForCreateRouteInput {
	s.IdentifierValue = &v
	return s
}

// SetResponseFilters sets the ResponseFilters field's value.
func (s *ApiSpecForCreateRouteInput) SetResponseFilters(v []*ResponseFilterForCreateRouteInput) *ApiSpecForCreateRouteInput {
	s.ResponseFilters = v
	return s
}

type ApiSpecForCreateRouteOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	ActionType *string `type:"string" json:",omitempty"`

	ActionValue *string `type:"string" json:",omitempty"`

	Extractors []*ExtractorForCreateRouteOutput `type:"list" json:",omitempty"`

	IdentifierType *int32 `type:"int32" json:",omitempty"`

	IdentifierValue *string `type:"string" json:",omitempty"`

	ResponseFilters []*ResponseFilterForCreateRouteOutput `type:"list" json:",omitempty"`
}

// String returns the string representation
func (s ApiSpecForCreateRouteOutput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s ApiSpecForCreateRouteOutput) GoString() string {
	return s.String()
}

// SetActionType sets the ActionType field's value.
func (s *ApiSpecForCreateRouteOutput) SetActionType(v string) *ApiSpecForCreateRouteOutput {
	s.ActionType = &v
	return s
}

// SetActionValue sets the ActionValue field's value.
func (s *ApiSpecForCreateRouteOutput) SetActionValue(v string) *ApiSpecForCreateRouteOutput {
	s.ActionValue = &v
	return s
}

// SetExtractors sets the Extractors field's value.
func (s *ApiSpecForCreateRouteOutput) SetExtractors(v []*ExtractorForCreateRouteOutput) *ApiSpecForCreateRouteOutput {
	s.Extractors = v
	return s
}

// SetIdentifierType sets the IdentifierType field's value.
func (s *ApiSpecForCreateRouteOutput) SetIdentifierType(v int32) *ApiSpecForCreateRouteOutput {
	s.IdentifierType = &v
	return s
}

// SetIdentifierValue sets the IdentifierValue field's value.
func (s *ApiSpecForCreateRouteOutput) SetIdentifierValue(v string) *ApiSpecForCreateRouteOutput {
	s.IdentifierValue = &v
	return s
}

// SetResponseFilters sets the ResponseFilters field's value.
func (s *ApiSpecForCreateRouteOutput) SetResponseFilters(v []*ResponseFilterForCreateRouteOutput) *ApiSpecForCreateRouteOutput {
	s.ResponseFilters = v
	return s
}

type AttributeForCreateRouteInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Field *string `type:"string" json:",omitempty"`

	Target *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s AttributeForCreateRouteInput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s AttributeForCreateRouteInput) GoString() string {
	return s.String()
}

// SetField sets the Field field's value.
func (s *AttributeForCreateRouteInput) SetField(v string) *AttributeForCreateRouteInput {
	s.Field = &v
	return s
}

// SetTarget sets the Target field's value.
func (s *AttributeForCreateRouteInput) SetTarget(v string) *AttributeForCreateRouteInput {
	s.Target = &v
	return s
}

type AttributeForCreateRouteOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Field *string `type:"string" json:",omitempty"`

	Target *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s AttributeForCreateRouteOutput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s AttributeForCreateRouteOutput) GoString() string {
	return s.String()
}

// SetField sets the Field field's value.
func (s *AttributeForCreateRouteOutput) SetField(v string) *AttributeForCreateRouteOutput {
	s.Field = &v
	return s
}

// SetTarget sets the Target field's value.
func (s *AttributeForCreateRouteOutput) SetTarget(v string) *AttributeForCreateRouteOutput {
	s.Target = &v
	return s
}

type CreateRouteInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Route *RouteForCreateRouteInput `type:"structure" json:",omitempty"`

	// ServiceName is a required field
	ServiceName *string `type:"string" json:",omitempty" required:"true"`
}

// String returns the string representation
func (s CreateRouteInput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s CreateRouteInput) GoString() string {
	return s.String()
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *CreateRouteInput) Validate() error {
	invalidParams := request.ErrInvalidParams{Context: "CreateRouteInput"}
	if s.ServiceName == nil {
		invalidParams.Add(request.NewErrParamRequired("ServiceName"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

// SetRoute sets the Route field's value.
func (s *CreateRouteInput) SetRoute(v *RouteForCreateRouteInput) *CreateRouteInput {
	s.Route = v
	return s
}

// SetServiceName sets the ServiceName field's value.
func (s *CreateRouteInput) SetServiceName(v string) *CreateRouteInput {
	s.ServiceName = &v
	return s
}

type CreateRouteOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata

	ApiSpec *ApiSpecForCreateRouteOutput `type:"structure" json:",omitempty"`

	AuthResourceType *string `type:"string" json:",omitempty"`

	CreatedAt *int64 `type:"int64" json:",omitempty"`

	Description *string `type:"string" json:",omitempty"`

	Method *string `type:"string" json:",omitempty"`

	Path *string `type:"string" json:",omitempty"`

	PathMatchType *string `type:"string" json:",omitempty"`

	PermissionPool *string `type:"string" json:",omitempty"`

	Priority *int32 `type:"int32" json:",omitempty"`

	ResourceType *string `type:"string" json:",omitempty"`

	RouteName *string `type:"string" json:",omitempty"`

	SourceTemplateId *string `type:"string" json:",omitempty"`

	Status *string `type:"string" json:",omitempty"`

	UpdatedAt *int64 `type:"int64" json:",omitempty"`
}

// String returns the string representation
func (s CreateRouteOutput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s CreateRouteOutput) GoString() string {
	return s.String()
}

// SetApiSpec sets the ApiSpec field's value.
func (s *CreateRouteOutput) SetApiSpec(v *ApiSpecForCreateRouteOutput) *CreateRouteOutput {
	s.ApiSpec = v
	return s
}

// SetAuthResourceType sets the AuthResourceType field's value.
func (s *CreateRouteOutput) SetAuthResourceType(v string) *CreateRouteOutput {
	s.AuthResourceType = &v
	return s
}

// SetCreatedAt sets the CreatedAt field's value.
func (s *CreateRouteOutput) SetCreatedAt(v int64) *CreateRouteOutput {
	s.CreatedAt = &v
	return s
}

// SetDescription sets the Description field's value.
func (s *CreateRouteOutput) SetDescription(v string) *CreateRouteOutput {
	s.Description = &v
	return s
}

// SetMethod sets the Method field's value.
func (s *CreateRouteOutput) SetMethod(v string) *CreateRouteOutput {
	s.Method = &v
	return s
}

// SetPath sets the Path field's value.
func (s *CreateRouteOutput) SetPath(v string) *CreateRouteOutput {
	s.Path = &v
	return s
}

// SetPathMatchType sets the PathMatchType field's value.
func (s *CreateRouteOutput) SetPathMatchType(v string) *CreateRouteOutput {
	s.PathMatchType = &v
	return s
}

// SetPermissionPool sets the PermissionPool field's value.
func (s *CreateRouteOutput) SetPermissionPool(v string) *CreateRouteOutput {
	s.PermissionPool = &v
	return s
}

// SetPriority sets the Priority field's value.
func (s *CreateRouteOutput) SetPriority(v int32) *CreateRouteOutput {
	s.Priority = &v
	return s
}

// SetResourceType sets the ResourceType field's value.
func (s *CreateRouteOutput) SetResourceType(v string) *CreateRouteOutput {
	s.ResourceType = &v
	return s
}

// SetRouteName sets the RouteName field's value.
func (s *CreateRouteOutput) SetRouteName(v string) *CreateRouteOutput {
	s.RouteName = &v
	return s
}

// SetSourceTemplateId sets the SourceTemplateId field's value.
func (s *CreateRouteOutput) SetSourceTemplateId(v string) *CreateRouteOutput {
	s.SourceTemplateId = &v
	return s
}

// SetStatus sets the Status field's value.
func (s *CreateRouteOutput) SetStatus(v string) *CreateRouteOutput {
	s.Status = &v
	return s
}

// SetUpdatedAt sets the UpdatedAt field's value.
func (s *CreateRouteOutput) SetUpdatedAt(v int64) *CreateRouteOutput {
	s.UpdatedAt = &v
	return s
}

type ExtractorForCreateRouteInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	IsAuth *bool `type:"boolean" json:",omitempty"`

	Path *string `type:"string" json:",omitempty"`

	ResourceType *string `type:"string" json:",omitempty"`

	Source *int32 `type:"int32" json:",omitempty"`
}

// String returns the string representation
func (s ExtractorForCreateRouteInput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s ExtractorForCreateRouteInput) GoString() string {
	return s.String()
}

// SetIsAuth sets the IsAuth field's value.
func (s *ExtractorForCreateRouteInput) SetIsAuth(v bool) *ExtractorForCreateRouteInput {
	s.IsAuth = &v
	return s
}

// SetPath sets the Path field's value.
func (s *ExtractorForCreateRouteInput) SetPath(v string) *ExtractorForCreateRouteInput {
	s.Path = &v
	return s
}

// SetResourceType sets the ResourceType field's value.
func (s *ExtractorForCreateRouteInput) SetResourceType(v string) *ExtractorForCreateRouteInput {
	s.ResourceType = &v
	return s
}

// SetSource sets the Source field's value.
func (s *ExtractorForCreateRouteInput) SetSource(v int32) *ExtractorForCreateRouteInput {
	s.Source = &v
	return s
}

type ExtractorForCreateRouteOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	IsAuth *bool `type:"boolean" json:",omitempty"`

	Path *string `type:"string" json:",omitempty"`

	ResourceType *string `type:"string" json:",omitempty"`

	Source *int32 `type:"int32" json:",omitempty"`
}

// String returns the string representation
func (s ExtractorForCreateRouteOutput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s ExtractorForCreateRouteOutput) GoString() string {
	return s.String()
}

// SetIsAuth sets the IsAuth field's value.
func (s *ExtractorForCreateRouteOutput) SetIsAuth(v bool) *ExtractorForCreateRouteOutput {
	s.IsAuth = &v
	return s
}

// SetPath sets the Path field's value.
func (s *ExtractorForCreateRouteOutput) SetPath(v string) *ExtractorForCreateRouteOutput {
	s.Path = &v
	return s
}

// SetResourceType sets the ResourceType field's value.
func (s *ExtractorForCreateRouteOutput) SetResourceType(v string) *ExtractorForCreateRouteOutput {
	s.ResourceType = &v
	return s
}

// SetSource sets the Source field's value.
func (s *ExtractorForCreateRouteOutput) SetSource(v int32) *ExtractorForCreateRouteOutput {
	s.Source = &v
	return s
}

type ResponseFilterForCreateRouteInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Attributes []*AttributeForCreateRouteInput `type:"list" json:",omitempty"`

	FilterPath *string `type:"string" json:",omitempty"`

	IdField *string `type:"string" json:",omitempty"`

	IsAuth *bool `type:"boolean" json:",omitempty"`

	Mode *int32 `type:"int32" json:",omitempty"`

	ResourcePath *string `type:"string" json:",omitempty"`

	ResourceType *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s ResponseFilterForCreateRouteInput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s ResponseFilterForCreateRouteInput) GoString() string {
	return s.String()
}

// SetAttributes sets the Attributes field's value.
func (s *ResponseFilterForCreateRouteInput) SetAttributes(v []*AttributeForCreateRouteInput) *ResponseFilterForCreateRouteInput {
	s.Attributes = v
	return s
}

// SetFilterPath sets the FilterPath field's value.
func (s *ResponseFilterForCreateRouteInput) SetFilterPath(v string) *ResponseFilterForCreateRouteInput {
	s.FilterPath = &v
	return s
}

// SetIdField sets the IdField field's value.
func (s *ResponseFilterForCreateRouteInput) SetIdField(v string) *ResponseFilterForCreateRouteInput {
	s.IdField = &v
	return s
}

// SetIsAuth sets the IsAuth field's value.
func (s *ResponseFilterForCreateRouteInput) SetIsAuth(v bool) *ResponseFilterForCreateRouteInput {
	s.IsAuth = &v
	return s
}

// SetMode sets the Mode field's value.
func (s *ResponseFilterForCreateRouteInput) SetMode(v int32) *ResponseFilterForCreateRouteInput {
	s.Mode = &v
	return s
}

// SetResourcePath sets the ResourcePath field's value.
func (s *ResponseFilterForCreateRouteInput) SetResourcePath(v string) *ResponseFilterForCreateRouteInput {
	s.ResourcePath = &v
	return s
}

// SetResourceType sets the ResourceType field's value.
func (s *ResponseFilterForCreateRouteInput) SetResourceType(v string) *ResponseFilterForCreateRouteInput {
	s.ResourceType = &v
	return s
}

type ResponseFilterForCreateRouteOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Attributes []*AttributeForCreateRouteOutput `type:"list" json:",omitempty"`

	FilterPath *string `type:"string" json:",omitempty"`

	IdField *string `type:"string" json:",omitempty"`

	IsAuth *bool `type:"boolean" json:",omitempty"`

	Mode *int32 `type:"int32" json:",omitempty"`

	ResourcePath *string `type:"string" json:",omitempty"`

	ResourceType *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s ResponseFilterForCreateRouteOutput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s ResponseFilterForCreateRouteOutput) GoString() string {
	return s.String()
}

// SetAttributes sets the Attributes field's value.
func (s *ResponseFilterForCreateRouteOutput) SetAttributes(v []*AttributeForCreateRouteOutput) *ResponseFilterForCreateRouteOutput {
	s.Attributes = v
	return s
}

// SetFilterPath sets the FilterPath field's value.
func (s *ResponseFilterForCreateRouteOutput) SetFilterPath(v string) *ResponseFilterForCreateRouteOutput {
	s.FilterPath = &v
	return s
}

// SetIdField sets the IdField field's value.
func (s *ResponseFilterForCreateRouteOutput) SetIdField(v string) *ResponseFilterForCreateRouteOutput {
	s.IdField = &v
	return s
}

// SetIsAuth sets the IsAuth field's value.
func (s *ResponseFilterForCreateRouteOutput) SetIsAuth(v bool) *ResponseFilterForCreateRouteOutput {
	s.IsAuth = &v
	return s
}

// SetMode sets the Mode field's value.
func (s *ResponseFilterForCreateRouteOutput) SetMode(v int32) *ResponseFilterForCreateRouteOutput {
	s.Mode = &v
	return s
}

// SetResourcePath sets the ResourcePath field's value.
func (s *ResponseFilterForCreateRouteOutput) SetResourcePath(v string) *ResponseFilterForCreateRouteOutput {
	s.ResourcePath = &v
	return s
}

// SetResourceType sets the ResourceType field's value.
func (s *ResponseFilterForCreateRouteOutput) SetResourceType(v string) *ResponseFilterForCreateRouteOutput {
	s.ResourceType = &v
	return s
}

type RouteForCreateRouteInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	ApiSpec *ApiSpecForCreateRouteInput `type:"structure" json:",omitempty"`

	AuthResourceType *string `type:"string" json:",omitempty"`

	Description *string `type:"string" json:",omitempty"`

	Method *string `type:"string" json:",omitempty"`

	Path *string `type:"string" json:",omitempty"`

	PathMatchType *string `type:"string" json:",omitempty"`

	PermissionPool *string `type:"string" json:",omitempty"`

	Priority *int32 `type:"int32" json:",omitempty"`

	ResourceType *string `type:"string" json:",omitempty"`

	RouteName *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s RouteForCreateRouteInput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s RouteForCreateRouteInput) GoString() string {
	return s.String()
}

// SetApiSpec sets the ApiSpec field's value.
func (s *RouteForCreateRouteInput) SetApiSpec(v *ApiSpecForCreateRouteInput) *RouteForCreateRouteInput {
	s.ApiSpec = v
	return s
}

// SetAuthResourceType sets the AuthResourceType field's value.
func (s *RouteForCreateRouteInput) SetAuthResourceType(v string) *RouteForCreateRouteInput {
	s.AuthResourceType = &v
	return s
}

// SetDescription sets the Description field's value.
func (s *RouteForCreateRouteInput) SetDescription(v string) *RouteForCreateRouteInput {
	s.Description = &v
	return s
}

// SetMethod sets the Method field's value.
func (s *RouteForCreateRouteInput) SetMethod(v string) *RouteForCreateRouteInput {
	s.Method = &v
	return s
}

// SetPath sets the Path field's value.
func (s *RouteForCreateRouteInput) SetPath(v string) *RouteForCreateRouteInput {
	s.Path = &v
	return s
}

// SetPathMatchType sets the PathMatchType field's value.
func (s *RouteForCreateRouteInput) SetPathMatchType(v string) *RouteForCreateRouteInput {
	s.PathMatchType = &v
	return s
}

// SetPermissionPool sets the PermissionPool field's value.
func (s *RouteForCreateRouteInput) SetPermissionPool(v string) *RouteForCreateRouteInput {
	s.PermissionPool = &v
	return s
}

// SetPriority sets the Priority field's value.
func (s *RouteForCreateRouteInput) SetPriority(v int32) *RouteForCreateRouteInput {
	s.Priority = &v
	return s
}

// SetResourceType sets the ResourceType field's value.
func (s *RouteForCreateRouteInput) SetResourceType(v string) *RouteForCreateRouteInput {
	s.ResourceType = &v
	return s
}

// SetRouteName sets the RouteName field's value.
func (s *RouteForCreateRouteInput) SetRouteName(v string) *RouteForCreateRouteInput {
	s.RouteName = &v
	return s
}
