// Code generated by volcengine with private/model/cli/gen-api/main.go. DO NOT EDIT.

package i18nopenapi

import (
	"github.com/volcengine/volcengine-go-sdk/volcengine"
	"github.com/volcengine/volcengine-go-sdk/volcengine/request"
	"github.com/volcengine/volcengine-go-sdk/volcengine/response"
	"github.com/volcengine/volcengine-go-sdk/volcengine/volcengineutil"
)

const opProjectUsersCommon = "ProjectUsers"

// ProjectUsersCommonRequest generates a "volcengine/request.Request" representing the
// client's request for the ProjectUsersCommon operation. The "output" return
// value will be populated with the ProjectUsersCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned ProjectUsersCommon Request to send the API call to the service.
// the "output" return value is not valid until after ProjectUsersCommon Send returns without error.
//
// See ProjectUsersCommon for more information on using the ProjectUsersCommon
// API call, and error handling.
//
//    // Example sending a request using the ProjectUsersCommonRequest method.
//    req, resp := client.ProjectUsersCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *I18NOPENAPI) ProjectUsersCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opProjectUsersCommon,
		HTTPMethod: "GET",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	return
}

// ProjectUsersCommon API operation for I18N_OPENAPI.
//
// Returns volcengineerr.Error for service API and SDK errors. Use runtime type assertions
// with volcengineerr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the VOLCENGINE API reference guide for I18N_OPENAPI's
// API operation ProjectUsersCommon for usage and error information.
func (c *I18NOPENAPI) ProjectUsersCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.ProjectUsersCommonRequest(input)
	return out, req.Send()
}

// ProjectUsersCommonWithContext is the same as ProjectUsersCommon with the addition of
// the ability to pass a context and additional request options.
//
// See ProjectUsersCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *I18NOPENAPI) ProjectUsersCommonWithContext(ctx volcengine.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.ProjectUsersCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opProjectUsers = "ProjectUsers"

// ProjectUsersRequest generates a "volcengine/request.Request" representing the
// client's request for the ProjectUsers operation. The "output" return
// value will be populated with the ProjectUsersCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned ProjectUsersCommon Request to send the API call to the service.
// the "output" return value is not valid until after ProjectUsersCommon Send returns without error.
//
// See ProjectUsers for more information on using the ProjectUsers
// API call, and error handling.
//
//    // Example sending a request using the ProjectUsersRequest method.
//    req, resp := client.ProjectUsersRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *I18NOPENAPI) ProjectUsersRequest(input *ProjectUsersInput) (req *request.Request, output *ProjectUsersOutput) {
	op := &request.Operation{
		Name:       opProjectUsers,
		HTTPMethod: "GET",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &ProjectUsersInput{}
	}

	output = &ProjectUsersOutput{}
	req = c.newRequest(op, input, output)

	return
}

// ProjectUsers API operation for I18N_OPENAPI.
//
// Returns volcengineerr.Error for service API and SDK errors. Use runtime type assertions
// with volcengineerr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the VOLCENGINE API reference guide for I18N_OPENAPI's
// API operation ProjectUsers for usage and error information.
func (c *I18NOPENAPI) ProjectUsers(input *ProjectUsersInput) (*ProjectUsersOutput, error) {
	req, out := c.ProjectUsersRequest(input)
	return out, req.Send()
}

// ProjectUsersWithContext is the same as ProjectUsers with the addition of
// the ability to pass a context and additional request options.
//
// See ProjectUsers for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *I18NOPENAPI) ProjectUsersWithContext(ctx volcengine.Context, input *ProjectUsersInput, opts ...request.Option) (*ProjectUsersOutput, error) {
	req, out := c.ProjectUsersRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type DataForProjectUsersOutput struct {
	_ struct{} `type:"structure"`

	CreateAt *string `type:"string" json:"createAt"`

	Role *int32 `type:"int32" json:"role"`

	UpdatedAt *string `type:"string" json:"updatedAt"`

	UserId *int32 `type:"int32" json:"userId"`
}

// String returns the string representation
func (s DataForProjectUsersOutput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s DataForProjectUsersOutput) GoString() string {
	return s.String()
}

// SetCreateAt sets the CreateAt field's value.
func (s *DataForProjectUsersOutput) SetCreateAt(v string) *DataForProjectUsersOutput {
	s.CreateAt = &v
	return s
}

// SetRole sets the Role field's value.
func (s *DataForProjectUsersOutput) SetRole(v int32) *DataForProjectUsersOutput {
	s.Role = &v
	return s
}

// SetUpdatedAt sets the UpdatedAt field's value.
func (s *DataForProjectUsersOutput) SetUpdatedAt(v string) *DataForProjectUsersOutput {
	s.UpdatedAt = &v
	return s
}

// SetUserId sets the UserId field's value.
func (s *DataForProjectUsersOutput) SetUserId(v int32) *DataForProjectUsersOutput {
	s.UserId = &v
	return s
}

type PaginationForProjectUsersOutput struct {
	_ struct{} `type:"structure"`

	Limit *int32 `type:"int32" json:"limit"`

	Offset *int32 `type:"int32" json:"offset"`
}

// String returns the string representation
func (s PaginationForProjectUsersOutput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s PaginationForProjectUsersOutput) GoString() string {
	return s.String()
}

// SetLimit sets the Limit field's value.
func (s *PaginationForProjectUsersOutput) SetLimit(v int32) *PaginationForProjectUsersOutput {
	s.Limit = &v
	return s
}

// SetOffset sets the Offset field's value.
func (s *PaginationForProjectUsersOutput) SetOffset(v int32) *PaginationForProjectUsersOutput {
	s.Offset = &v
	return s
}

type ProjectUsersInput struct {
	_ struct{} `type:"structure"`

	Limit *int32 `locationName:"limit" type:"int32"`

	Offset *int32 `locationName:"offset" type:"int32"`

	// ProjectId is a required field
	ProjectId *int32 `locationName:"projectId" type:"int32" required:"true"`
}

// String returns the string representation
func (s ProjectUsersInput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s ProjectUsersInput) GoString() string {
	return s.String()
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *ProjectUsersInput) Validate() error {
	invalidParams := request.ErrInvalidParams{Context: "ProjectUsersInput"}
	if s.ProjectId == nil {
		invalidParams.Add(request.NewErrParamRequired("ProjectId"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

// SetLimit sets the Limit field's value.
func (s *ProjectUsersInput) SetLimit(v int32) *ProjectUsersInput {
	s.Limit = &v
	return s
}

// SetOffset sets the Offset field's value.
func (s *ProjectUsersInput) SetOffset(v int32) *ProjectUsersInput {
	s.Offset = &v
	return s
}

// SetProjectId sets the ProjectId field's value.
func (s *ProjectUsersInput) SetProjectId(v int32) *ProjectUsersInput {
	s.ProjectId = &v
	return s
}

type ProjectUsersOutput struct {
	_ struct{} `type:"structure"`

	Metadata *response.ResponseMetadata

	Data *DataForProjectUsersOutput `type:"structure" json:"data"`

	Pagination *PaginationForProjectUsersOutput `type:"structure" json:"pagination"`

	Total *int32 `type:"int32" json:"total"`
}

// String returns the string representation
func (s ProjectUsersOutput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s ProjectUsersOutput) GoString() string {
	return s.String()
}

// SetData sets the Data field's value.
func (s *ProjectUsersOutput) SetData(v *DataForProjectUsersOutput) *ProjectUsersOutput {
	s.Data = v
	return s
}

// SetPagination sets the Pagination field's value.
func (s *ProjectUsersOutput) SetPagination(v *PaginationForProjectUsersOutput) *ProjectUsersOutput {
	s.Pagination = v
	return s
}

// SetTotal sets the Total field's value.
func (s *ProjectUsersOutput) SetTotal(v int32) *ProjectUsersOutput {
	s.Total = &v
	return s
}
