// Code generated by volcengine with private/model/cli/gen-api/main.go. DO NOT EDIT.

package iam

import (
	"github.com/volcengine/volcengine-go-sdk/volcengine"
	"github.com/volcengine/volcengine-go-sdk/volcengine/request"
	"github.com/volcengine/volcengine-go-sdk/volcengine/response"
	"github.com/volcengine/volcengine-go-sdk/volcengine/volcengineutil"
)

const opUpdateAllowedIPAddressesCommon = "UpdateAllowedIPAddresses"

// UpdateAllowedIPAddressesCommonRequest generates a "volcengine/request.Request" representing the
// client's request for the UpdateAllowedIPAddressesCommon operation. The "output" return
// value will be populated with the UpdateAllowedIPAddressesCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned UpdateAllowedIPAddressesCommon Request to send the API call to the service.
// the "output" return value is not valid until after UpdateAllowedIPAddressesCommon Send returns without error.
//
// See UpdateAllowedIPAddressesCommon for more information on using the UpdateAllowedIPAddressesCommon
// API call, and error handling.
//
//    // Example sending a request using the UpdateAllowedIPAddressesCommonRequest method.
//    req, resp := client.UpdateAllowedIPAddressesCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *IAM) UpdateAllowedIPAddressesCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opUpdateAllowedIPAddressesCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// UpdateAllowedIPAddressesCommon API operation for IAM.
//
// Returns volcengineerr.Error for service API and SDK errors. Use runtime type assertions
// with volcengineerr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the VOLCENGINE API reference guide for IAM's
// API operation UpdateAllowedIPAddressesCommon for usage and error information.
func (c *IAM) UpdateAllowedIPAddressesCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.UpdateAllowedIPAddressesCommonRequest(input)
	return out, req.Send()
}

// UpdateAllowedIPAddressesCommonWithContext is the same as UpdateAllowedIPAddressesCommon with the addition of
// the ability to pass a context and additional request options.
//
// See UpdateAllowedIPAddressesCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *IAM) UpdateAllowedIPAddressesCommonWithContext(ctx volcengine.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.UpdateAllowedIPAddressesCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opUpdateAllowedIPAddresses = "UpdateAllowedIPAddresses"

// UpdateAllowedIPAddressesRequest generates a "volcengine/request.Request" representing the
// client's request for the UpdateAllowedIPAddresses operation. The "output" return
// value will be populated with the UpdateAllowedIPAddressesCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned UpdateAllowedIPAddressesCommon Request to send the API call to the service.
// the "output" return value is not valid until after UpdateAllowedIPAddressesCommon Send returns without error.
//
// See UpdateAllowedIPAddresses for more information on using the UpdateAllowedIPAddresses
// API call, and error handling.
//
//    // Example sending a request using the UpdateAllowedIPAddressesRequest method.
//    req, resp := client.UpdateAllowedIPAddressesRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *IAM) UpdateAllowedIPAddressesRequest(input *UpdateAllowedIPAddressesInput) (req *request.Request, output *UpdateAllowedIPAddressesOutput) {
	op := &request.Operation{
		Name:       opUpdateAllowedIPAddresses,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &UpdateAllowedIPAddressesInput{}
	}

	output = &UpdateAllowedIPAddressesOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// UpdateAllowedIPAddresses API operation for IAM.
//
// Returns volcengineerr.Error for service API and SDK errors. Use runtime type assertions
// with volcengineerr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the VOLCENGINE API reference guide for IAM's
// API operation UpdateAllowedIPAddresses for usage and error information.
func (c *IAM) UpdateAllowedIPAddresses(input *UpdateAllowedIPAddressesInput) (*UpdateAllowedIPAddressesOutput, error) {
	req, out := c.UpdateAllowedIPAddressesRequest(input)
	return out, req.Send()
}

// UpdateAllowedIPAddressesWithContext is the same as UpdateAllowedIPAddresses with the addition of
// the ability to pass a context and additional request options.
//
// See UpdateAllowedIPAddresses for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *IAM) UpdateAllowedIPAddressesWithContext(ctx volcengine.Context, input *UpdateAllowedIPAddressesInput, opts ...request.Option) (*UpdateAllowedIPAddressesOutput, error) {
	req, out := c.UpdateAllowedIPAddressesRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type IPListForUpdateAllowedIPAddressesInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Description *string `type:"string" json:",omitempty"`

	IP *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s IPListForUpdateAllowedIPAddressesInput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s IPListForUpdateAllowedIPAddressesInput) GoString() string {
	return s.String()
}

// SetDescription sets the Description field's value.
func (s *IPListForUpdateAllowedIPAddressesInput) SetDescription(v string) *IPListForUpdateAllowedIPAddressesInput {
	s.Description = &v
	return s
}

// SetIP sets the IP field's value.
func (s *IPListForUpdateAllowedIPAddressesInput) SetIP(v string) *IPListForUpdateAllowedIPAddressesInput {
	s.IP = &v
	return s
}

type UpdateAllowedIPAddressesInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	// EnableIPList is a required field
	EnableIPList *bool `type:"boolean" json:",omitempty" required:"true"`

	IPList []*IPListForUpdateAllowedIPAddressesInput `type:"list" json:",omitempty"`
}

// String returns the string representation
func (s UpdateAllowedIPAddressesInput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s UpdateAllowedIPAddressesInput) GoString() string {
	return s.String()
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *UpdateAllowedIPAddressesInput) Validate() error {
	invalidParams := request.ErrInvalidParams{Context: "UpdateAllowedIPAddressesInput"}
	if s.EnableIPList == nil {
		invalidParams.Add(request.NewErrParamRequired("EnableIPList"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

// SetEnableIPList sets the EnableIPList field's value.
func (s *UpdateAllowedIPAddressesInput) SetEnableIPList(v bool) *UpdateAllowedIPAddressesInput {
	s.EnableIPList = &v
	return s
}

// SetIPList sets the IPList field's value.
func (s *UpdateAllowedIPAddressesInput) SetIPList(v []*IPListForUpdateAllowedIPAddressesInput) *UpdateAllowedIPAddressesInput {
	s.IPList = v
	return s
}

type UpdateAllowedIPAddressesOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata
}

// String returns the string representation
func (s UpdateAllowedIPAddressesOutput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s UpdateAllowedIPAddressesOutput) GoString() string {
	return s.String()
}
