// Code generated by volcengine with private/model/cli/gen-api/main.go. DO NOT EDIT.

package insight

import (
	"github.com/volcengine/volcengine-go-sdk/volcengine"
	"github.com/volcengine/volcengine-go-sdk/volcengine/request"
	"github.com/volcengine/volcengine-go-sdk/volcengine/response"
	"github.com/volcengine/volcengine-go-sdk/volcengine/volcengineutil"
)

const opExpertInvokeAPICommon = "ExpertInvokeAPI"

// ExpertInvokeAPICommonRequest generates a "volcengine/request.Request" representing the
// client's request for the ExpertInvokeAPICommon operation. The "output" return
// value will be populated with the ExpertInvokeAPICommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned ExpertInvokeAPICommon Request to send the API call to the service.
// the "output" return value is not valid until after ExpertInvokeAPICommon Send returns without error.
//
// See ExpertInvokeAPICommon for more information on using the ExpertInvokeAPICommon
// API call, and error handling.
//
//    // Example sending a request using the ExpertInvokeAPICommonRequest method.
//    req, resp := client.ExpertInvokeAPICommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *INSIGHT) ExpertInvokeAPICommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opExpertInvokeAPICommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// ExpertInvokeAPICommon API operation for INSIGHT.
//
// Returns volcengineerr.Error for service API and SDK errors. Use runtime type assertions
// with volcengineerr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the VOLCENGINE API reference guide for INSIGHT's
// API operation ExpertInvokeAPICommon for usage and error information.
func (c *INSIGHT) ExpertInvokeAPICommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.ExpertInvokeAPICommonRequest(input)
	return out, req.Send()
}

// ExpertInvokeAPICommonWithContext is the same as ExpertInvokeAPICommon with the addition of
// the ability to pass a context and additional request options.
//
// See ExpertInvokeAPICommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *INSIGHT) ExpertInvokeAPICommonWithContext(ctx volcengine.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.ExpertInvokeAPICommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opExpertInvokeAPI = "ExpertInvokeAPI"

// ExpertInvokeAPIRequest generates a "volcengine/request.Request" representing the
// client's request for the ExpertInvokeAPI operation. The "output" return
// value will be populated with the ExpertInvokeAPICommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned ExpertInvokeAPICommon Request to send the API call to the service.
// the "output" return value is not valid until after ExpertInvokeAPICommon Send returns without error.
//
// See ExpertInvokeAPI for more information on using the ExpertInvokeAPI
// API call, and error handling.
//
//    // Example sending a request using the ExpertInvokeAPIRequest method.
//    req, resp := client.ExpertInvokeAPIRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *INSIGHT) ExpertInvokeAPIRequest(input *ExpertInvokeAPIInput) (req *request.Request, output *ExpertInvokeAPIOutput) {
	op := &request.Operation{
		Name:       opExpertInvokeAPI,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &ExpertInvokeAPIInput{}
	}

	output = &ExpertInvokeAPIOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// ExpertInvokeAPI API operation for INSIGHT.
//
// Returns volcengineerr.Error for service API and SDK errors. Use runtime type assertions
// with volcengineerr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the VOLCENGINE API reference guide for INSIGHT's
// API operation ExpertInvokeAPI for usage and error information.
func (c *INSIGHT) ExpertInvokeAPI(input *ExpertInvokeAPIInput) (*ExpertInvokeAPIOutput, error) {
	req, out := c.ExpertInvokeAPIRequest(input)
	return out, req.Send()
}

// ExpertInvokeAPIWithContext is the same as ExpertInvokeAPI with the addition of
// the ability to pass a context and additional request options.
//
// See ExpertInvokeAPI for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *INSIGHT) ExpertInvokeAPIWithContext(ctx volcengine.Context, input *ExpertInvokeAPIInput, opts ...request.Option) (*ExpertInvokeAPIOutput, error) {
	req, out := c.ExpertInvokeAPIRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type ExpertInvokeAPIInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Asr *string `type:"string" json:",omitempty"`

	ClassifiedAgentId *int64 `type:"int64" json:",omitempty"`

	ConfigId *int64 `type:"int64" json:",omitempty"`

	Content *string `type:"string" json:",omitempty"`

	DomainLevel *int32 `type:"int32" json:",omitempty"`

	// ExpertId is a required field
	ExpertId *int64 `type:"int64" json:",omitempty" required:"true"`

	FansCnt *int64 `type:"int64" json:",omitempty"`

	Ocr *string `type:"string" json:",omitempty"`

	OriginId *int64 `type:"int64" json:",omitempty"`

	Title *string `type:"string" json:",omitempty"`

	Url *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s ExpertInvokeAPIInput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s ExpertInvokeAPIInput) GoString() string {
	return s.String()
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *ExpertInvokeAPIInput) Validate() error {
	invalidParams := request.ErrInvalidParams{Context: "ExpertInvokeAPIInput"}
	if s.ExpertId == nil {
		invalidParams.Add(request.NewErrParamRequired("ExpertId"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

// SetAsr sets the Asr field's value.
func (s *ExpertInvokeAPIInput) SetAsr(v string) *ExpertInvokeAPIInput {
	s.Asr = &v
	return s
}

// SetClassifiedAgentId sets the ClassifiedAgentId field's value.
func (s *ExpertInvokeAPIInput) SetClassifiedAgentId(v int64) *ExpertInvokeAPIInput {
	s.ClassifiedAgentId = &v
	return s
}

// SetConfigId sets the ConfigId field's value.
func (s *ExpertInvokeAPIInput) SetConfigId(v int64) *ExpertInvokeAPIInput {
	s.ConfigId = &v
	return s
}

// SetContent sets the Content field's value.
func (s *ExpertInvokeAPIInput) SetContent(v string) *ExpertInvokeAPIInput {
	s.Content = &v
	return s
}

// SetDomainLevel sets the DomainLevel field's value.
func (s *ExpertInvokeAPIInput) SetDomainLevel(v int32) *ExpertInvokeAPIInput {
	s.DomainLevel = &v
	return s
}

// SetExpertId sets the ExpertId field's value.
func (s *ExpertInvokeAPIInput) SetExpertId(v int64) *ExpertInvokeAPIInput {
	s.ExpertId = &v
	return s
}

// SetFansCnt sets the FansCnt field's value.
func (s *ExpertInvokeAPIInput) SetFansCnt(v int64) *ExpertInvokeAPIInput {
	s.FansCnt = &v
	return s
}

// SetOcr sets the Ocr field's value.
func (s *ExpertInvokeAPIInput) SetOcr(v string) *ExpertInvokeAPIInput {
	s.Ocr = &v
	return s
}

// SetOriginId sets the OriginId field's value.
func (s *ExpertInvokeAPIInput) SetOriginId(v int64) *ExpertInvokeAPIInput {
	s.OriginId = &v
	return s
}

// SetTitle sets the Title field's value.
func (s *ExpertInvokeAPIInput) SetTitle(v string) *ExpertInvokeAPIInput {
	s.Title = &v
	return s
}

// SetUrl sets the Url field's value.
func (s *ExpertInvokeAPIInput) SetUrl(v string) *ExpertInvokeAPIInput {
	s.Url = &v
	return s
}

type ExpertInvokeAPIOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata

	Result *ResultForExpertInvokeAPIOutput `type:"structure" json:",omitempty"`
}

// String returns the string representation
func (s ExpertInvokeAPIOutput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s ExpertInvokeAPIOutput) GoString() string {
	return s.String()
}

// SetResult sets the Result field's value.
func (s *ExpertInvokeAPIOutput) SetResult(v *ResultForExpertInvokeAPIOutput) *ExpertInvokeAPIOutput {
	s.Result = v
	return s
}

type ResultForExpertInvokeAPIOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Asr *string `type:"string" json:",omitempty"`

	Content *string `type:"string" json:",omitempty"`

	DomainLevel *int32 `type:"int32" json:",omitempty"`

	FansCnt *int64 `type:"int64" json:",omitempty"`

	HasRisk *bool `type:"boolean" json:",omitempty"`

	Ocr *string `type:"string" json:",omitempty"`

	OriginId *string `type:"string" json:",omitempty"`

	Related *bool `type:"boolean" json:",omitempty"`

	RelatedReason *string `type:"string" json:",omitempty"`

	RiskLevel *string `type:"string" json:",omitempty"`

	RiskReason *string `type:"string" json:",omitempty"`

	RiskTags []*string `type:"list" json:",omitempty"`

	Suggestion *string `type:"string" json:",omitempty"`

	Summary *string `type:"string" json:",omitempty"`

	Title *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s ResultForExpertInvokeAPIOutput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s ResultForExpertInvokeAPIOutput) GoString() string {
	return s.String()
}

// SetAsr sets the Asr field's value.
func (s *ResultForExpertInvokeAPIOutput) SetAsr(v string) *ResultForExpertInvokeAPIOutput {
	s.Asr = &v
	return s
}

// SetContent sets the Content field's value.
func (s *ResultForExpertInvokeAPIOutput) SetContent(v string) *ResultForExpertInvokeAPIOutput {
	s.Content = &v
	return s
}

// SetDomainLevel sets the DomainLevel field's value.
func (s *ResultForExpertInvokeAPIOutput) SetDomainLevel(v int32) *ResultForExpertInvokeAPIOutput {
	s.DomainLevel = &v
	return s
}

// SetFansCnt sets the FansCnt field's value.
func (s *ResultForExpertInvokeAPIOutput) SetFansCnt(v int64) *ResultForExpertInvokeAPIOutput {
	s.FansCnt = &v
	return s
}

// SetHasRisk sets the HasRisk field's value.
func (s *ResultForExpertInvokeAPIOutput) SetHasRisk(v bool) *ResultForExpertInvokeAPIOutput {
	s.HasRisk = &v
	return s
}

// SetOcr sets the Ocr field's value.
func (s *ResultForExpertInvokeAPIOutput) SetOcr(v string) *ResultForExpertInvokeAPIOutput {
	s.Ocr = &v
	return s
}

// SetOriginId sets the OriginId field's value.
func (s *ResultForExpertInvokeAPIOutput) SetOriginId(v string) *ResultForExpertInvokeAPIOutput {
	s.OriginId = &v
	return s
}

// SetRelated sets the Related field's value.
func (s *ResultForExpertInvokeAPIOutput) SetRelated(v bool) *ResultForExpertInvokeAPIOutput {
	s.Related = &v
	return s
}

// SetRelatedReason sets the RelatedReason field's value.
func (s *ResultForExpertInvokeAPIOutput) SetRelatedReason(v string) *ResultForExpertInvokeAPIOutput {
	s.RelatedReason = &v
	return s
}

// SetRiskLevel sets the RiskLevel field's value.
func (s *ResultForExpertInvokeAPIOutput) SetRiskLevel(v string) *ResultForExpertInvokeAPIOutput {
	s.RiskLevel = &v
	return s
}

// SetRiskReason sets the RiskReason field's value.
func (s *ResultForExpertInvokeAPIOutput) SetRiskReason(v string) *ResultForExpertInvokeAPIOutput {
	s.RiskReason = &v
	return s
}

// SetRiskTags sets the RiskTags field's value.
func (s *ResultForExpertInvokeAPIOutput) SetRiskTags(v []*string) *ResultForExpertInvokeAPIOutput {
	s.RiskTags = v
	return s
}

// SetSuggestion sets the Suggestion field's value.
func (s *ResultForExpertInvokeAPIOutput) SetSuggestion(v string) *ResultForExpertInvokeAPIOutput {
	s.Suggestion = &v
	return s
}

// SetSummary sets the Summary field's value.
func (s *ResultForExpertInvokeAPIOutput) SetSummary(v string) *ResultForExpertInvokeAPIOutput {
	s.Summary = &v
	return s
}

// SetTitle sets the Title field's value.
func (s *ResultForExpertInvokeAPIOutput) SetTitle(v string) *ResultForExpertInvokeAPIOutput {
	s.Title = &v
	return s
}
