// Code generated by volcengine with private/model/cli/gen-api/main.go. DO NOT EDIT.

package apig

import (
	"github.com/volcengine/volcengine-go-sdk/volcengine"
	"github.com/volcengine/volcengine-go-sdk/volcengine/request"
	"github.com/volcengine/volcengine-go-sdk/volcengine/response"
	"github.com/volcengine/volcengine-go-sdk/volcengine/volcengineutil"
)

const opGetCustomDomainCommon = "GetCustomDomain"

// GetCustomDomainCommonRequest generates a "volcengine/request.Request" representing the
// client's request for the GetCustomDomainCommon operation. The "output" return
// value will be populated with the GetCustomDomainCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned GetCustomDomainCommon Request to send the API call to the service.
// the "output" return value is not valid until after GetCustomDomainCommon Send returns without error.
//
// See GetCustomDomainCommon for more information on using the GetCustomDomainCommon
// API call, and error handling.
//
//    // Example sending a request using the GetCustomDomainCommonRequest method.
//    req, resp := client.GetCustomDomainCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *APIG) GetCustomDomainCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opGetCustomDomainCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// GetCustomDomainCommon API operation for APIG.
//
// Returns volcengineerr.Error for service API and SDK errors. Use runtime type assertions
// with volcengineerr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the VOLCENGINE API reference guide for APIG's
// API operation GetCustomDomainCommon for usage and error information.
func (c *APIG) GetCustomDomainCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.GetCustomDomainCommonRequest(input)
	return out, req.Send()
}

// GetCustomDomainCommonWithContext is the same as GetCustomDomainCommon with the addition of
// the ability to pass a context and additional request options.
//
// See GetCustomDomainCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *APIG) GetCustomDomainCommonWithContext(ctx volcengine.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.GetCustomDomainCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opGetCustomDomain = "GetCustomDomain"

// GetCustomDomainRequest generates a "volcengine/request.Request" representing the
// client's request for the GetCustomDomain operation. The "output" return
// value will be populated with the GetCustomDomainCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned GetCustomDomainCommon Request to send the API call to the service.
// the "output" return value is not valid until after GetCustomDomainCommon Send returns without error.
//
// See GetCustomDomain for more information on using the GetCustomDomain
// API call, and error handling.
//
//    // Example sending a request using the GetCustomDomainRequest method.
//    req, resp := client.GetCustomDomainRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *APIG) GetCustomDomainRequest(input *GetCustomDomainInput) (req *request.Request, output *GetCustomDomainOutput) {
	op := &request.Operation{
		Name:       opGetCustomDomain,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &GetCustomDomainInput{}
	}

	output = &GetCustomDomainOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// GetCustomDomain API operation for APIG.
//
// Returns volcengineerr.Error for service API and SDK errors. Use runtime type assertions
// with volcengineerr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the VOLCENGINE API reference guide for APIG's
// API operation GetCustomDomain for usage and error information.
func (c *APIG) GetCustomDomain(input *GetCustomDomainInput) (*GetCustomDomainOutput, error) {
	req, out := c.GetCustomDomainRequest(input)
	return out, req.Send()
}

// GetCustomDomainWithContext is the same as GetCustomDomain with the addition of
// the ability to pass a context and additional request options.
//
// See GetCustomDomain for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *APIG) GetCustomDomainWithContext(ctx volcengine.Context, input *GetCustomDomainInput, opts ...request.Option) (*GetCustomDomainOutput, error) {
	req, out := c.GetCustomDomainRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type CustomDomainForGetCustomDomainOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	CertificateId *string `type:"string" json:",omitempty"`

	Comments *string `type:"string" json:",omitempty"`

	CreateTime *string `type:"string" json:",omitempty"`

	Domain *string `type:"string" json:",omitempty"`

	Id *string `type:"string" json:",omitempty"`

	Protocol []*string `type:"list" json:",omitempty"`

	SSLRedirect *bool `type:"boolean" json:",omitempty"`

	ServiceId *string `type:"string" json:",omitempty"`

	Status *string `type:"string" json:",omitempty"`

	UpdateTime *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s CustomDomainForGetCustomDomainOutput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s CustomDomainForGetCustomDomainOutput) GoString() string {
	return s.String()
}

// SetCertificateId sets the CertificateId field's value.
func (s *CustomDomainForGetCustomDomainOutput) SetCertificateId(v string) *CustomDomainForGetCustomDomainOutput {
	s.CertificateId = &v
	return s
}

// SetComments sets the Comments field's value.
func (s *CustomDomainForGetCustomDomainOutput) SetComments(v string) *CustomDomainForGetCustomDomainOutput {
	s.Comments = &v
	return s
}

// SetCreateTime sets the CreateTime field's value.
func (s *CustomDomainForGetCustomDomainOutput) SetCreateTime(v string) *CustomDomainForGetCustomDomainOutput {
	s.CreateTime = &v
	return s
}

// SetDomain sets the Domain field's value.
func (s *CustomDomainForGetCustomDomainOutput) SetDomain(v string) *CustomDomainForGetCustomDomainOutput {
	s.Domain = &v
	return s
}

// SetId sets the Id field's value.
func (s *CustomDomainForGetCustomDomainOutput) SetId(v string) *CustomDomainForGetCustomDomainOutput {
	s.Id = &v
	return s
}

// SetProtocol sets the Protocol field's value.
func (s *CustomDomainForGetCustomDomainOutput) SetProtocol(v []*string) *CustomDomainForGetCustomDomainOutput {
	s.Protocol = v
	return s
}

// SetSSLRedirect sets the SSLRedirect field's value.
func (s *CustomDomainForGetCustomDomainOutput) SetSSLRedirect(v bool) *CustomDomainForGetCustomDomainOutput {
	s.SSLRedirect = &v
	return s
}

// SetServiceId sets the ServiceId field's value.
func (s *CustomDomainForGetCustomDomainOutput) SetServiceId(v string) *CustomDomainForGetCustomDomainOutput {
	s.ServiceId = &v
	return s
}

// SetStatus sets the Status field's value.
func (s *CustomDomainForGetCustomDomainOutput) SetStatus(v string) *CustomDomainForGetCustomDomainOutput {
	s.Status = &v
	return s
}

// SetUpdateTime sets the UpdateTime field's value.
func (s *CustomDomainForGetCustomDomainOutput) SetUpdateTime(v string) *CustomDomainForGetCustomDomainOutput {
	s.UpdateTime = &v
	return s
}

type GetCustomDomainInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	// Id is a required field
	Id *string `type:"string" json:",omitempty" required:"true"`
}

// String returns the string representation
func (s GetCustomDomainInput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s GetCustomDomainInput) GoString() string {
	return s.String()
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *GetCustomDomainInput) Validate() error {
	invalidParams := request.ErrInvalidParams{Context: "GetCustomDomainInput"}
	if s.Id == nil {
		invalidParams.Add(request.NewErrParamRequired("Id"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

// SetId sets the Id field's value.
func (s *GetCustomDomainInput) SetId(v string) *GetCustomDomainInput {
	s.Id = &v
	return s
}

type GetCustomDomainOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata

	CustomDomain *CustomDomainForGetCustomDomainOutput `type:"structure" json:",omitempty"`
}

// String returns the string representation
func (s GetCustomDomainOutput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s GetCustomDomainOutput) GoString() string {
	return s.String()
}

// SetCustomDomain sets the CustomDomain field's value.
func (s *GetCustomDomainOutput) SetCustomDomain(v *CustomDomainForGetCustomDomainOutput) *GetCustomDomainOutput {
	s.CustomDomain = v
	return s
}
