// Code generated by volcengine with private/model/cli/gen-api/main.go. DO NOT EDIT.

package veenedge

import (
	"github.com/volcengine/volcengine-go-sdk/volcengine"
	"github.com/volcengine/volcengine-go-sdk/volcengine/request"
	"github.com/volcengine/volcengine-go-sdk/volcengine/response"
	"github.com/volcengine/volcengine-go-sdk/volcengine/volcengineutil"
)

const opUnassociateRouteTableWithSubnetsCommon = "UnassociateRouteTableWithSubnets"

// UnassociateRouteTableWithSubnetsCommonRequest generates a "volcengine/request.Request" representing the
// client's request for the UnassociateRouteTableWithSubnetsCommon operation. The "output" return
// value will be populated with the UnassociateRouteTableWithSubnetsCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned UnassociateRouteTableWithSubnetsCommon Request to send the API call to the service.
// the "output" return value is not valid until after UnassociateRouteTableWithSubnetsCommon Send returns without error.
//
// See UnassociateRouteTableWithSubnetsCommon for more information on using the UnassociateRouteTableWithSubnetsCommon
// API call, and error handling.
//
//    // Example sending a request using the UnassociateRouteTableWithSubnetsCommonRequest method.
//    req, resp := client.UnassociateRouteTableWithSubnetsCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *VEENEDGE) UnassociateRouteTableWithSubnetsCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opUnassociateRouteTableWithSubnetsCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// UnassociateRouteTableWithSubnetsCommon API operation for VEENEDGE.
//
// Returns volcengineerr.Error for service API and SDK errors. Use runtime type assertions
// with volcengineerr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the VOLCENGINE API reference guide for VEENEDGE's
// API operation UnassociateRouteTableWithSubnetsCommon for usage and error information.
func (c *VEENEDGE) UnassociateRouteTableWithSubnetsCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.UnassociateRouteTableWithSubnetsCommonRequest(input)
	return out, req.Send()
}

// UnassociateRouteTableWithSubnetsCommonWithContext is the same as UnassociateRouteTableWithSubnetsCommon with the addition of
// the ability to pass a context and additional request options.
//
// See UnassociateRouteTableWithSubnetsCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *VEENEDGE) UnassociateRouteTableWithSubnetsCommonWithContext(ctx volcengine.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.UnassociateRouteTableWithSubnetsCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opUnassociateRouteTableWithSubnets = "UnassociateRouteTableWithSubnets"

// UnassociateRouteTableWithSubnetsRequest generates a "volcengine/request.Request" representing the
// client's request for the UnassociateRouteTableWithSubnets operation. The "output" return
// value will be populated with the UnassociateRouteTableWithSubnetsCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned UnassociateRouteTableWithSubnetsCommon Request to send the API call to the service.
// the "output" return value is not valid until after UnassociateRouteTableWithSubnetsCommon Send returns without error.
//
// See UnassociateRouteTableWithSubnets for more information on using the UnassociateRouteTableWithSubnets
// API call, and error handling.
//
//    // Example sending a request using the UnassociateRouteTableWithSubnetsRequest method.
//    req, resp := client.UnassociateRouteTableWithSubnetsRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *VEENEDGE) UnassociateRouteTableWithSubnetsRequest(input *UnassociateRouteTableWithSubnetsInput) (req *request.Request, output *UnassociateRouteTableWithSubnetsOutput) {
	op := &request.Operation{
		Name:       opUnassociateRouteTableWithSubnets,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &UnassociateRouteTableWithSubnetsInput{}
	}

	output = &UnassociateRouteTableWithSubnetsOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// UnassociateRouteTableWithSubnets API operation for VEENEDGE.
//
// Returns volcengineerr.Error for service API and SDK errors. Use runtime type assertions
// with volcengineerr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the VOLCENGINE API reference guide for VEENEDGE's
// API operation UnassociateRouteTableWithSubnets for usage and error information.
func (c *VEENEDGE) UnassociateRouteTableWithSubnets(input *UnassociateRouteTableWithSubnetsInput) (*UnassociateRouteTableWithSubnetsOutput, error) {
	req, out := c.UnassociateRouteTableWithSubnetsRequest(input)
	return out, req.Send()
}

// UnassociateRouteTableWithSubnetsWithContext is the same as UnassociateRouteTableWithSubnets with the addition of
// the ability to pass a context and additional request options.
//
// See UnassociateRouteTableWithSubnets for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *VEENEDGE) UnassociateRouteTableWithSubnetsWithContext(ctx volcengine.Context, input *UnassociateRouteTableWithSubnetsInput, opts ...request.Option) (*UnassociateRouteTableWithSubnetsOutput, error) {
	req, out := c.UnassociateRouteTableWithSubnetsRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type UnassociateRouteTableWithSubnetsInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	// Route_table_identity is a required field
	Route_table_identity *string `type:"string" json:"route_table_identity,omitempty" required:"true"`

	Subnet_identity_list []*string `type:"list" json:"subnet_identity_list"`
}

// String returns the string representation
func (s UnassociateRouteTableWithSubnetsInput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s UnassociateRouteTableWithSubnetsInput) GoString() string {
	return s.String()
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *UnassociateRouteTableWithSubnetsInput) Validate() error {
	invalidParams := request.ErrInvalidParams{Context: "UnassociateRouteTableWithSubnetsInput"}
	if s.Route_table_identity == nil {
		invalidParams.Add(request.NewErrParamRequired("Route_table_identity"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

// SetRoute_table_identity sets the Route_table_identity field's value.
func (s *UnassociateRouteTableWithSubnetsInput) SetRoute_table_identity(v string) *UnassociateRouteTableWithSubnetsInput {
	s.Route_table_identity = &v
	return s
}

// SetSubnet_identity_list sets the Subnet_identity_list field's value.
func (s *UnassociateRouteTableWithSubnetsInput) SetSubnet_identity_list(v []*string) *UnassociateRouteTableWithSubnetsInput {
	s.Subnet_identity_list = v
	return s
}

type UnassociateRouteTableWithSubnetsOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata
}

// String returns the string representation
func (s UnassociateRouteTableWithSubnetsOutput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s UnassociateRouteTableWithSubnetsOutput) GoString() string {
	return s.String()
}
