// Code generated by volcengine with private/model/cli/gen-api/main.go. DO NOT EDIT.

package transitrouter

import (
	"github.com/volcengine/volcengine-go-sdk/volcengine"
	"github.com/volcengine/volcengine-go-sdk/volcengine/request"
	"github.com/volcengine/volcengine-go-sdk/volcengine/response"
	"github.com/volcengine/volcengine-go-sdk/volcengine/volcengineutil"
)

const opDissociateTransitRouterMulticastDomainCommon = "DissociateTransitRouterMulticastDomain"

// DissociateTransitRouterMulticastDomainCommonRequest generates a "volcengine/request.Request" representing the
// client's request for the DissociateTransitRouterMulticastDomainCommon operation. The "output" return
// value will be populated with the DissociateTransitRouterMulticastDomainCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned DissociateTransitRouterMulticastDomainCommon Request to send the API call to the service.
// the "output" return value is not valid until after DissociateTransitRouterMulticastDomainCommon Send returns without error.
//
// See DissociateTransitRouterMulticastDomainCommon for more information on using the DissociateTransitRouterMulticastDomainCommon
// API call, and error handling.
//
//    // Example sending a request using the DissociateTransitRouterMulticastDomainCommonRequest method.
//    req, resp := client.DissociateTransitRouterMulticastDomainCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *TRANSITROUTER) DissociateTransitRouterMulticastDomainCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opDissociateTransitRouterMulticastDomainCommon,
		HTTPMethod: "GET",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	return
}

// DissociateTransitRouterMulticastDomainCommon API operation for TRANSITROUTER.
//
// Returns volcengineerr.Error for service API and SDK errors. Use runtime type assertions
// with volcengineerr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the VOLCENGINE API reference guide for TRANSITROUTER's
// API operation DissociateTransitRouterMulticastDomainCommon for usage and error information.
func (c *TRANSITROUTER) DissociateTransitRouterMulticastDomainCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.DissociateTransitRouterMulticastDomainCommonRequest(input)
	return out, req.Send()
}

// DissociateTransitRouterMulticastDomainCommonWithContext is the same as DissociateTransitRouterMulticastDomainCommon with the addition of
// the ability to pass a context and additional request options.
//
// See DissociateTransitRouterMulticastDomainCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *TRANSITROUTER) DissociateTransitRouterMulticastDomainCommonWithContext(ctx volcengine.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.DissociateTransitRouterMulticastDomainCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opDissociateTransitRouterMulticastDomain = "DissociateTransitRouterMulticastDomain"

// DissociateTransitRouterMulticastDomainRequest generates a "volcengine/request.Request" representing the
// client's request for the DissociateTransitRouterMulticastDomain operation. The "output" return
// value will be populated with the DissociateTransitRouterMulticastDomainCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned DissociateTransitRouterMulticastDomainCommon Request to send the API call to the service.
// the "output" return value is not valid until after DissociateTransitRouterMulticastDomainCommon Send returns without error.
//
// See DissociateTransitRouterMulticastDomain for more information on using the DissociateTransitRouterMulticastDomain
// API call, and error handling.
//
//    // Example sending a request using the DissociateTransitRouterMulticastDomainRequest method.
//    req, resp := client.DissociateTransitRouterMulticastDomainRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *TRANSITROUTER) DissociateTransitRouterMulticastDomainRequest(input *DissociateTransitRouterMulticastDomainInput) (req *request.Request, output *DissociateTransitRouterMulticastDomainOutput) {
	op := &request.Operation{
		Name:       opDissociateTransitRouterMulticastDomain,
		HTTPMethod: "GET",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &DissociateTransitRouterMulticastDomainInput{}
	}

	output = &DissociateTransitRouterMulticastDomainOutput{}
	req = c.newRequest(op, input, output)

	return
}

// DissociateTransitRouterMulticastDomain API operation for TRANSITROUTER.
//
// Returns volcengineerr.Error for service API and SDK errors. Use runtime type assertions
// with volcengineerr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the VOLCENGINE API reference guide for TRANSITROUTER's
// API operation DissociateTransitRouterMulticastDomain for usage and error information.
func (c *TRANSITROUTER) DissociateTransitRouterMulticastDomain(input *DissociateTransitRouterMulticastDomainInput) (*DissociateTransitRouterMulticastDomainOutput, error) {
	req, out := c.DissociateTransitRouterMulticastDomainRequest(input)
	return out, req.Send()
}

// DissociateTransitRouterMulticastDomainWithContext is the same as DissociateTransitRouterMulticastDomain with the addition of
// the ability to pass a context and additional request options.
//
// See DissociateTransitRouterMulticastDomain for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *TRANSITROUTER) DissociateTransitRouterMulticastDomainWithContext(ctx volcengine.Context, input *DissociateTransitRouterMulticastDomainInput, opts ...request.Option) (*DissociateTransitRouterMulticastDomainOutput, error) {
	req, out := c.DissociateTransitRouterMulticastDomainRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type DissociateTransitRouterMulticastDomainInput struct {
	_ struct{} `type:"structure"`

	// SubnetId is a required field
	SubnetId *string `type:"string" required:"true"`

	// TransitRouterAttachmentId is a required field
	TransitRouterAttachmentId *string `type:"string" required:"true"`

	// TransitRouterMulticastDomainId is a required field
	TransitRouterMulticastDomainId *string `type:"string" required:"true"`
}

// String returns the string representation
func (s DissociateTransitRouterMulticastDomainInput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s DissociateTransitRouterMulticastDomainInput) GoString() string {
	return s.String()
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *DissociateTransitRouterMulticastDomainInput) Validate() error {
	invalidParams := request.ErrInvalidParams{Context: "DissociateTransitRouterMulticastDomainInput"}
	if s.SubnetId == nil {
		invalidParams.Add(request.NewErrParamRequired("SubnetId"))
	}
	if s.TransitRouterAttachmentId == nil {
		invalidParams.Add(request.NewErrParamRequired("TransitRouterAttachmentId"))
	}
	if s.TransitRouterMulticastDomainId == nil {
		invalidParams.Add(request.NewErrParamRequired("TransitRouterMulticastDomainId"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

// SetSubnetId sets the SubnetId field's value.
func (s *DissociateTransitRouterMulticastDomainInput) SetSubnetId(v string) *DissociateTransitRouterMulticastDomainInput {
	s.SubnetId = &v
	return s
}

// SetTransitRouterAttachmentId sets the TransitRouterAttachmentId field's value.
func (s *DissociateTransitRouterMulticastDomainInput) SetTransitRouterAttachmentId(v string) *DissociateTransitRouterMulticastDomainInput {
	s.TransitRouterAttachmentId = &v
	return s
}

// SetTransitRouterMulticastDomainId sets the TransitRouterMulticastDomainId field's value.
func (s *DissociateTransitRouterMulticastDomainInput) SetTransitRouterMulticastDomainId(v string) *DissociateTransitRouterMulticastDomainInput {
	s.TransitRouterMulticastDomainId = &v
	return s
}

type DissociateTransitRouterMulticastDomainOutput struct {
	_ struct{} `type:"structure"`

	Metadata *response.ResponseMetadata
}

// String returns the string representation
func (s DissociateTransitRouterMulticastDomainOutput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s DissociateTransitRouterMulticastDomainOutput) GoString() string {
	return s.String()
}
