// Code generated by volcengine with private/model/cli/gen-api/main.go. DO NOT EDIT.

package configservice

import (
	"github.com/volcengine/volcengine-go-sdk/volcengine"
	"github.com/volcengine/volcengine-go-sdk/volcengine/request"
	"github.com/volcengine/volcengine-go-sdk/volcengine/response"
	"github.com/volcengine/volcengine-go-sdk/volcengine/volcengineutil"
)

const opDescribeAccountGroupComplianceByRulesCommon = "DescribeAccountGroupComplianceByRules"

// DescribeAccountGroupComplianceByRulesCommonRequest generates a "volcengine/request.Request" representing the
// client's request for the DescribeAccountGroupComplianceByRulesCommon operation. The "output" return
// value will be populated with the DescribeAccountGroupComplianceByRulesCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned DescribeAccountGroupComplianceByRulesCommon Request to send the API call to the service.
// the "output" return value is not valid until after DescribeAccountGroupComplianceByRulesCommon Send returns without error.
//
// See DescribeAccountGroupComplianceByRulesCommon for more information on using the DescribeAccountGroupComplianceByRulesCommon
// API call, and error handling.
//
//    // Example sending a request using the DescribeAccountGroupComplianceByRulesCommonRequest method.
//    req, resp := client.DescribeAccountGroupComplianceByRulesCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *ConfigService) DescribeAccountGroupComplianceByRulesCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opDescribeAccountGroupComplianceByRulesCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// DescribeAccountGroupComplianceByRulesCommon API operation for CONFIG.
//
// Returns volcengineerr.Error for service API and SDK errors. Use runtime type assertions
// with volcengineerr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the VOLCENGINE API reference guide for CONFIG's
// API operation DescribeAccountGroupComplianceByRulesCommon for usage and error information.
func (c *ConfigService) DescribeAccountGroupComplianceByRulesCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.DescribeAccountGroupComplianceByRulesCommonRequest(input)
	return out, req.Send()
}

// DescribeAccountGroupComplianceByRulesCommonWithContext is the same as DescribeAccountGroupComplianceByRulesCommon with the addition of
// the ability to pass a context and additional request options.
//
// See DescribeAccountGroupComplianceByRulesCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *ConfigService) DescribeAccountGroupComplianceByRulesCommonWithContext(ctx volcengine.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.DescribeAccountGroupComplianceByRulesCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opDescribeAccountGroupComplianceByRules = "DescribeAccountGroupComplianceByRules"

// DescribeAccountGroupComplianceByRulesRequest generates a "volcengine/request.Request" representing the
// client's request for the DescribeAccountGroupComplianceByRules operation. The "output" return
// value will be populated with the DescribeAccountGroupComplianceByRulesCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned DescribeAccountGroupComplianceByRulesCommon Request to send the API call to the service.
// the "output" return value is not valid until after DescribeAccountGroupComplianceByRulesCommon Send returns without error.
//
// See DescribeAccountGroupComplianceByRules for more information on using the DescribeAccountGroupComplianceByRules
// API call, and error handling.
//
//    // Example sending a request using the DescribeAccountGroupComplianceByRulesRequest method.
//    req, resp := client.DescribeAccountGroupComplianceByRulesRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *ConfigService) DescribeAccountGroupComplianceByRulesRequest(input *DescribeAccountGroupComplianceByRulesInput) (req *request.Request, output *DescribeAccountGroupComplianceByRulesOutput) {
	op := &request.Operation{
		Name:       opDescribeAccountGroupComplianceByRules,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &DescribeAccountGroupComplianceByRulesInput{}
	}

	output = &DescribeAccountGroupComplianceByRulesOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// DescribeAccountGroupComplianceByRules API operation for CONFIG.
//
// Returns volcengineerr.Error for service API and SDK errors. Use runtime type assertions
// with volcengineerr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the VOLCENGINE API reference guide for CONFIG's
// API operation DescribeAccountGroupComplianceByRules for usage and error information.
func (c *ConfigService) DescribeAccountGroupComplianceByRules(input *DescribeAccountGroupComplianceByRulesInput) (*DescribeAccountGroupComplianceByRulesOutput, error) {
	req, out := c.DescribeAccountGroupComplianceByRulesRequest(input)
	return out, req.Send()
}

// DescribeAccountGroupComplianceByRulesWithContext is the same as DescribeAccountGroupComplianceByRules with the addition of
// the ability to pass a context and additional request options.
//
// See DescribeAccountGroupComplianceByRules for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *ConfigService) DescribeAccountGroupComplianceByRulesWithContext(ctx volcengine.Context, input *DescribeAccountGroupComplianceByRulesInput, opts ...request.Option) (*DescribeAccountGroupComplianceByRulesOutput, error) {
	req, out := c.DescribeAccountGroupComplianceByRulesRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type ComplianceByRuleForDescribeAccountGroupComplianceByRulesOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Compliance *ComplianceForDescribeAccountGroupComplianceByRulesOutput `type:"structure" json:",omitempty"`

	RuleId *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s ComplianceByRuleForDescribeAccountGroupComplianceByRulesOutput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s ComplianceByRuleForDescribeAccountGroupComplianceByRulesOutput) GoString() string {
	return s.String()
}

// SetCompliance sets the Compliance field's value.
func (s *ComplianceByRuleForDescribeAccountGroupComplianceByRulesOutput) SetCompliance(v *ComplianceForDescribeAccountGroupComplianceByRulesOutput) *ComplianceByRuleForDescribeAccountGroupComplianceByRulesOutput {
	s.Compliance = v
	return s
}

// SetRuleId sets the RuleId field's value.
func (s *ComplianceByRuleForDescribeAccountGroupComplianceByRulesOutput) SetRuleId(v string) *ComplianceByRuleForDescribeAccountGroupComplianceByRulesOutput {
	s.RuleId = &v
	return s
}

type ComplianceForDescribeAccountGroupComplianceByRulesOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	ComplianceStatistics []*ComplianceStatisticForDescribeAccountGroupComplianceByRulesOutput `type:"list" json:",omitempty"`

	ComplianceType *string `type:"string" json:",omitempty" enum:"EnumOfComplianceTypeForDescribeAccountGroupComplianceByRulesOutput"`
}

// String returns the string representation
func (s ComplianceForDescribeAccountGroupComplianceByRulesOutput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s ComplianceForDescribeAccountGroupComplianceByRulesOutput) GoString() string {
	return s.String()
}

// SetComplianceStatistics sets the ComplianceStatistics field's value.
func (s *ComplianceForDescribeAccountGroupComplianceByRulesOutput) SetComplianceStatistics(v []*ComplianceStatisticForDescribeAccountGroupComplianceByRulesOutput) *ComplianceForDescribeAccountGroupComplianceByRulesOutput {
	s.ComplianceStatistics = v
	return s
}

// SetComplianceType sets the ComplianceType field's value.
func (s *ComplianceForDescribeAccountGroupComplianceByRulesOutput) SetComplianceType(v string) *ComplianceForDescribeAccountGroupComplianceByRulesOutput {
	s.ComplianceType = &v
	return s
}

type ComplianceStatisticForDescribeAccountGroupComplianceByRulesOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	ComplianceType *string `type:"string" json:",omitempty" enum:"EnumOfComplianceTypeForDescribeAccountGroupComplianceByRulesOutput"`

	Count *int32 `type:"int32" json:",omitempty"`

	Relation *string `type:"string" json:",omitempty" enum:"EnumOfRelationForDescribeAccountGroupComplianceByRulesOutput"`
}

// String returns the string representation
func (s ComplianceStatisticForDescribeAccountGroupComplianceByRulesOutput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s ComplianceStatisticForDescribeAccountGroupComplianceByRulesOutput) GoString() string {
	return s.String()
}

// SetComplianceType sets the ComplianceType field's value.
func (s *ComplianceStatisticForDescribeAccountGroupComplianceByRulesOutput) SetComplianceType(v string) *ComplianceStatisticForDescribeAccountGroupComplianceByRulesOutput {
	s.ComplianceType = &v
	return s
}

// SetCount sets the Count field's value.
func (s *ComplianceStatisticForDescribeAccountGroupComplianceByRulesOutput) SetCount(v int32) *ComplianceStatisticForDescribeAccountGroupComplianceByRulesOutput {
	s.Count = &v
	return s
}

// SetRelation sets the Relation field's value.
func (s *ComplianceStatisticForDescribeAccountGroupComplianceByRulesOutput) SetRelation(v string) *ComplianceStatisticForDescribeAccountGroupComplianceByRulesOutput {
	s.Relation = &v
	return s
}

type DescribeAccountGroupComplianceByRulesInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	// AccountGroupId is a required field
	AccountGroupId *string `type:"string" json:",omitempty" required:"true"`

	ResourceAccountId *int64 `type:"int64" json:",omitempty"`

	RuleIds []*string `type:"list" json:",omitempty"`
}

// String returns the string representation
func (s DescribeAccountGroupComplianceByRulesInput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s DescribeAccountGroupComplianceByRulesInput) GoString() string {
	return s.String()
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *DescribeAccountGroupComplianceByRulesInput) Validate() error {
	invalidParams := request.ErrInvalidParams{Context: "DescribeAccountGroupComplianceByRulesInput"}
	if s.AccountGroupId == nil {
		invalidParams.Add(request.NewErrParamRequired("AccountGroupId"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

// SetAccountGroupId sets the AccountGroupId field's value.
func (s *DescribeAccountGroupComplianceByRulesInput) SetAccountGroupId(v string) *DescribeAccountGroupComplianceByRulesInput {
	s.AccountGroupId = &v
	return s
}

// SetResourceAccountId sets the ResourceAccountId field's value.
func (s *DescribeAccountGroupComplianceByRulesInput) SetResourceAccountId(v int64) *DescribeAccountGroupComplianceByRulesInput {
	s.ResourceAccountId = &v
	return s
}

// SetRuleIds sets the RuleIds field's value.
func (s *DescribeAccountGroupComplianceByRulesInput) SetRuleIds(v []*string) *DescribeAccountGroupComplianceByRulesInput {
	s.RuleIds = v
	return s
}

type DescribeAccountGroupComplianceByRulesOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata

	ComplianceByRules []*ComplianceByRuleForDescribeAccountGroupComplianceByRulesOutput `type:"list" json:",omitempty"`
}

// String returns the string representation
func (s DescribeAccountGroupComplianceByRulesOutput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s DescribeAccountGroupComplianceByRulesOutput) GoString() string {
	return s.String()
}

// SetComplianceByRules sets the ComplianceByRules field's value.
func (s *DescribeAccountGroupComplianceByRulesOutput) SetComplianceByRules(v []*ComplianceByRuleForDescribeAccountGroupComplianceByRulesOutput) *DescribeAccountGroupComplianceByRulesOutput {
	s.ComplianceByRules = v
	return s
}

const (
	// EnumOfComplianceTypeForDescribeAccountGroupComplianceByRulesOutputInsufficientData is a EnumOfComplianceTypeForDescribeAccountGroupComplianceByRulesOutput enum value
	EnumOfComplianceTypeForDescribeAccountGroupComplianceByRulesOutputInsufficientData = "InsufficientData"

	// EnumOfComplianceTypeForDescribeAccountGroupComplianceByRulesOutputError is a EnumOfComplianceTypeForDescribeAccountGroupComplianceByRulesOutput enum value
	EnumOfComplianceTypeForDescribeAccountGroupComplianceByRulesOutputError = "Error"

	// EnumOfComplianceTypeForDescribeAccountGroupComplianceByRulesOutputNonCompliant is a EnumOfComplianceTypeForDescribeAccountGroupComplianceByRulesOutput enum value
	EnumOfComplianceTypeForDescribeAccountGroupComplianceByRulesOutputNonCompliant = "NonCompliant"

	// EnumOfComplianceTypeForDescribeAccountGroupComplianceByRulesOutputCompliant is a EnumOfComplianceTypeForDescribeAccountGroupComplianceByRulesOutput enum value
	EnumOfComplianceTypeForDescribeAccountGroupComplianceByRulesOutputCompliant = "Compliant"

	// EnumOfComplianceTypeForDescribeAccountGroupComplianceByRulesOutputExempt is a EnumOfComplianceTypeForDescribeAccountGroupComplianceByRulesOutput enum value
	EnumOfComplianceTypeForDescribeAccountGroupComplianceByRulesOutputExempt = "Exempt"
)

const (
	// EnumOfRelationForDescribeAccountGroupComplianceByRulesOutputEq is a EnumOfRelationForDescribeAccountGroupComplianceByRulesOutput enum value
	EnumOfRelationForDescribeAccountGroupComplianceByRulesOutputEq = "Eq"

	// EnumOfRelationForDescribeAccountGroupComplianceByRulesOutputGte is a EnumOfRelationForDescribeAccountGroupComplianceByRulesOutput enum value
	EnumOfRelationForDescribeAccountGroupComplianceByRulesOutputGte = "Gte"
)
