// Code generated by volcengine with private/model/cli/gen-api/main.go. DO NOT EDIT.

package vpc

import (
	"github.com/volcengine/volcengine-go-sdk/volcengine"
	"github.com/volcengine/volcengine-go-sdk/volcengine/request"
	"github.com/volcengine/volcengine-go-sdk/volcengine/response"
	"github.com/volcengine/volcengine-go-sdk/volcengine/volcengineutil"
)

const opAttachIpv4GatewayCommon = "AttachIpv4Gateway"

// AttachIpv4GatewayCommonRequest generates a "volcengine/request.Request" representing the
// client's request for the AttachIpv4GatewayCommon operation. The "output" return
// value will be populated with the AttachIpv4GatewayCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned AttachIpv4GatewayCommon Request to send the API call to the service.
// the "output" return value is not valid until after AttachIpv4GatewayCommon Send returns without error.
//
// See AttachIpv4GatewayCommon for more information on using the AttachIpv4GatewayCommon
// API call, and error handling.
//
//    // Example sending a request using the AttachIpv4GatewayCommonRequest method.
//    req, resp := client.AttachIpv4GatewayCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *VPC) AttachIpv4GatewayCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opAttachIpv4GatewayCommon,
		HTTPMethod: "GET",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	return
}

// AttachIpv4GatewayCommon API operation for VPC.
//
// Returns volcengineerr.Error for service API and SDK errors. Use runtime type assertions
// with volcengineerr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the VOLCENGINE API reference guide for VPC's
// API operation AttachIpv4GatewayCommon for usage and error information.
func (c *VPC) AttachIpv4GatewayCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.AttachIpv4GatewayCommonRequest(input)
	return out, req.Send()
}

// AttachIpv4GatewayCommonWithContext is the same as AttachIpv4GatewayCommon with the addition of
// the ability to pass a context and additional request options.
//
// See AttachIpv4GatewayCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *VPC) AttachIpv4GatewayCommonWithContext(ctx volcengine.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.AttachIpv4GatewayCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opAttachIpv4Gateway = "AttachIpv4Gateway"

// AttachIpv4GatewayRequest generates a "volcengine/request.Request" representing the
// client's request for the AttachIpv4Gateway operation. The "output" return
// value will be populated with the AttachIpv4GatewayCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned AttachIpv4GatewayCommon Request to send the API call to the service.
// the "output" return value is not valid until after AttachIpv4GatewayCommon Send returns without error.
//
// See AttachIpv4Gateway for more information on using the AttachIpv4Gateway
// API call, and error handling.
//
//    // Example sending a request using the AttachIpv4GatewayRequest method.
//    req, resp := client.AttachIpv4GatewayRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *VPC) AttachIpv4GatewayRequest(input *AttachIpv4GatewayInput) (req *request.Request, output *AttachIpv4GatewayOutput) {
	op := &request.Operation{
		Name:       opAttachIpv4Gateway,
		HTTPMethod: "GET",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &AttachIpv4GatewayInput{}
	}

	output = &AttachIpv4GatewayOutput{}
	req = c.newRequest(op, input, output)

	return
}

// AttachIpv4Gateway API operation for VPC.
//
// Returns volcengineerr.Error for service API and SDK errors. Use runtime type assertions
// with volcengineerr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the VOLCENGINE API reference guide for VPC's
// API operation AttachIpv4Gateway for usage and error information.
func (c *VPC) AttachIpv4Gateway(input *AttachIpv4GatewayInput) (*AttachIpv4GatewayOutput, error) {
	req, out := c.AttachIpv4GatewayRequest(input)
	return out, req.Send()
}

// AttachIpv4GatewayWithContext is the same as AttachIpv4Gateway with the addition of
// the ability to pass a context and additional request options.
//
// See AttachIpv4Gateway for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *VPC) AttachIpv4GatewayWithContext(ctx volcengine.Context, input *AttachIpv4GatewayInput, opts ...request.Option) (*AttachIpv4GatewayOutput, error) {
	req, out := c.AttachIpv4GatewayRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type AttachIpv4GatewayInput struct {
	_ struct{} `type:"structure"`

	ClientToken *string `type:"string"`

	// Ipv4GatewayId is a required field
	Ipv4GatewayId *string `type:"string" required:"true"`

	// VpcId is a required field
	VpcId *string `type:"string" required:"true"`
}

// String returns the string representation
func (s AttachIpv4GatewayInput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s AttachIpv4GatewayInput) GoString() string {
	return s.String()
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *AttachIpv4GatewayInput) Validate() error {
	invalidParams := request.ErrInvalidParams{Context: "AttachIpv4GatewayInput"}
	if s.Ipv4GatewayId == nil {
		invalidParams.Add(request.NewErrParamRequired("Ipv4GatewayId"))
	}
	if s.VpcId == nil {
		invalidParams.Add(request.NewErrParamRequired("VpcId"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

// SetClientToken sets the ClientToken field's value.
func (s *AttachIpv4GatewayInput) SetClientToken(v string) *AttachIpv4GatewayInput {
	s.ClientToken = &v
	return s
}

// SetIpv4GatewayId sets the Ipv4GatewayId field's value.
func (s *AttachIpv4GatewayInput) SetIpv4GatewayId(v string) *AttachIpv4GatewayInput {
	s.Ipv4GatewayId = &v
	return s
}

// SetVpcId sets the VpcId field's value.
func (s *AttachIpv4GatewayInput) SetVpcId(v string) *AttachIpv4GatewayInput {
	s.VpcId = &v
	return s
}

type AttachIpv4GatewayOutput struct {
	_ struct{} `type:"structure"`

	Metadata *response.ResponseMetadata

	RequestId *string `type:"string"`
}

// String returns the string representation
func (s AttachIpv4GatewayOutput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s AttachIpv4GatewayOutput) GoString() string {
	return s.String()
}

// SetRequestId sets the RequestId field's value.
func (s *AttachIpv4GatewayOutput) SetRequestId(v string) *AttachIpv4GatewayOutput {
	s.RequestId = &v
	return s
}
