// Code generated by volcengine with private/model/cli/gen-api/main.go. DO NOT EDIT.

package volcobserve

import (
	"github.com/volcengine/volcengine-go-sdk/volcengine"
	"github.com/volcengine/volcengine-go-sdk/volcengine/request"
	"github.com/volcengine/volcengine-go-sdk/volcengine/response"
	"github.com/volcengine/volcengine-go-sdk/volcengine/volcengineutil"
)

const opUpdateContactsWithContactGroupsCommon = "UpdateContactsWithContactGroups"

// UpdateContactsWithContactGroupsCommonRequest generates a "volcengine/request.Request" representing the
// client's request for the UpdateContactsWithContactGroupsCommon operation. The "output" return
// value will be populated with the UpdateContactsWithContactGroupsCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned UpdateContactsWithContactGroupsCommon Request to send the API call to the service.
// the "output" return value is not valid until after UpdateContactsWithContactGroupsCommon Send returns without error.
//
// See UpdateContactsWithContactGroupsCommon for more information on using the UpdateContactsWithContactGroupsCommon
// API call, and error handling.
//
//    // Example sending a request using the UpdateContactsWithContactGroupsCommonRequest method.
//    req, resp := client.UpdateContactsWithContactGroupsCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *VOLCOBSERVE) UpdateContactsWithContactGroupsCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opUpdateContactsWithContactGroupsCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// UpdateContactsWithContactGroupsCommon API operation for VOLC_OBSERVE.
//
// Returns volcengineerr.Error for service API and SDK errors. Use runtime type assertions
// with volcengineerr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the VOLCENGINE API reference guide for VOLC_OBSERVE's
// API operation UpdateContactsWithContactGroupsCommon for usage and error information.
func (c *VOLCOBSERVE) UpdateContactsWithContactGroupsCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.UpdateContactsWithContactGroupsCommonRequest(input)
	return out, req.Send()
}

// UpdateContactsWithContactGroupsCommonWithContext is the same as UpdateContactsWithContactGroupsCommon with the addition of
// the ability to pass a context and additional request options.
//
// See UpdateContactsWithContactGroupsCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *VOLCOBSERVE) UpdateContactsWithContactGroupsCommonWithContext(ctx volcengine.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.UpdateContactsWithContactGroupsCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opUpdateContactsWithContactGroups = "UpdateContactsWithContactGroups"

// UpdateContactsWithContactGroupsRequest generates a "volcengine/request.Request" representing the
// client's request for the UpdateContactsWithContactGroups operation. The "output" return
// value will be populated with the UpdateContactsWithContactGroupsCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned UpdateContactsWithContactGroupsCommon Request to send the API call to the service.
// the "output" return value is not valid until after UpdateContactsWithContactGroupsCommon Send returns without error.
//
// See UpdateContactsWithContactGroups for more information on using the UpdateContactsWithContactGroups
// API call, and error handling.
//
//    // Example sending a request using the UpdateContactsWithContactGroupsRequest method.
//    req, resp := client.UpdateContactsWithContactGroupsRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *VOLCOBSERVE) UpdateContactsWithContactGroupsRequest(input *UpdateContactsWithContactGroupsInput) (req *request.Request, output *UpdateContactsWithContactGroupsOutput) {
	op := &request.Operation{
		Name:       opUpdateContactsWithContactGroups,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &UpdateContactsWithContactGroupsInput{}
	}

	output = &UpdateContactsWithContactGroupsOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// UpdateContactsWithContactGroups API operation for VOLC_OBSERVE.
//
// Returns volcengineerr.Error for service API and SDK errors. Use runtime type assertions
// with volcengineerr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the VOLCENGINE API reference guide for VOLC_OBSERVE's
// API operation UpdateContactsWithContactGroups for usage and error information.
func (c *VOLCOBSERVE) UpdateContactsWithContactGroups(input *UpdateContactsWithContactGroupsInput) (*UpdateContactsWithContactGroupsOutput, error) {
	req, out := c.UpdateContactsWithContactGroupsRequest(input)
	return out, req.Send()
}

// UpdateContactsWithContactGroupsWithContext is the same as UpdateContactsWithContactGroups with the addition of
// the ability to pass a context and additional request options.
//
// See UpdateContactsWithContactGroups for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *VOLCOBSERVE) UpdateContactsWithContactGroupsWithContext(ctx volcengine.Context, input *UpdateContactsWithContactGroupsInput, opts ...request.Option) (*UpdateContactsWithContactGroupsOutput, error) {
	req, out := c.UpdateContactsWithContactGroupsRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type UpdateContactsWithContactGroupsInput struct {
	_ struct{} `type:"structure"`

	ContactGroupIds []*string `type:"list"`

	// Id is a required field
	Id *string `type:"string" required:"true"`
}

// String returns the string representation
func (s UpdateContactsWithContactGroupsInput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s UpdateContactsWithContactGroupsInput) GoString() string {
	return s.String()
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *UpdateContactsWithContactGroupsInput) Validate() error {
	invalidParams := request.ErrInvalidParams{Context: "UpdateContactsWithContactGroupsInput"}
	if s.Id == nil {
		invalidParams.Add(request.NewErrParamRequired("Id"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

// SetContactGroupIds sets the ContactGroupIds field's value.
func (s *UpdateContactsWithContactGroupsInput) SetContactGroupIds(v []*string) *UpdateContactsWithContactGroupsInput {
	s.ContactGroupIds = v
	return s
}

// SetId sets the Id field's value.
func (s *UpdateContactsWithContactGroupsInput) SetId(v string) *UpdateContactsWithContactGroupsInput {
	s.Id = &v
	return s
}

type UpdateContactsWithContactGroupsOutput struct {
	_ struct{} `type:"structure"`

	Metadata *response.ResponseMetadata

	Data []*string `type:"list"`
}

// String returns the string representation
func (s UpdateContactsWithContactGroupsOutput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s UpdateContactsWithContactGroupsOutput) GoString() string {
	return s.String()
}

// SetData sets the Data field's value.
func (s *UpdateContactsWithContactGroupsOutput) SetData(v []*string) *UpdateContactsWithContactGroupsOutput {
	s.Data = v
	return s
}
