// Code generated by volcengine with private/model/cli/gen-api/main.go. DO NOT EDIT.

package bmq

import (
	"github.com/volcengine/volcengine-go-sdk/volcengine"
	"github.com/volcengine/volcengine-go-sdk/volcengine/request"
	"github.com/volcengine/volcengine-go-sdk/volcengine/response"
	"github.com/volcengine/volcengine-go-sdk/volcengine/volcengineutil"
)

const opSearchInstancesCommon = "SearchInstances"

// SearchInstancesCommonRequest generates a "volcengine/request.Request" representing the
// client's request for the SearchInstancesCommon operation. The "output" return
// value will be populated with the SearchInstancesCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned SearchInstancesCommon Request to send the API call to the service.
// the "output" return value is not valid until after SearchInstancesCommon Send returns without error.
//
// See SearchInstancesCommon for more information on using the SearchInstancesCommon
// API call, and error handling.
//
//    // Example sending a request using the SearchInstancesCommonRequest method.
//    req, resp := client.SearchInstancesCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *BMQ) SearchInstancesCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opSearchInstancesCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// SearchInstancesCommon API operation for BMQ.
//
// Returns volcengineerr.Error for service API and SDK errors. Use runtime type assertions
// with volcengineerr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the VOLCENGINE API reference guide for BMQ's
// API operation SearchInstancesCommon for usage and error information.
func (c *BMQ) SearchInstancesCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.SearchInstancesCommonRequest(input)
	return out, req.Send()
}

// SearchInstancesCommonWithContext is the same as SearchInstancesCommon with the addition of
// the ability to pass a context and additional request options.
//
// See SearchInstancesCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *BMQ) SearchInstancesCommonWithContext(ctx volcengine.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.SearchInstancesCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opSearchInstances = "SearchInstances"

// SearchInstancesRequest generates a "volcengine/request.Request" representing the
// client's request for the SearchInstances operation. The "output" return
// value will be populated with the SearchInstancesCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned SearchInstancesCommon Request to send the API call to the service.
// the "output" return value is not valid until after SearchInstancesCommon Send returns without error.
//
// See SearchInstances for more information on using the SearchInstances
// API call, and error handling.
//
//    // Example sending a request using the SearchInstancesRequest method.
//    req, resp := client.SearchInstancesRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *BMQ) SearchInstancesRequest(input *SearchInstancesInput) (req *request.Request, output *SearchInstancesOutput) {
	op := &request.Operation{
		Name:       opSearchInstances,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &SearchInstancesInput{}
	}

	output = &SearchInstancesOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// SearchInstances API operation for BMQ.
//
// Returns volcengineerr.Error for service API and SDK errors. Use runtime type assertions
// with volcengineerr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the VOLCENGINE API reference guide for BMQ's
// API operation SearchInstances for usage and error information.
func (c *BMQ) SearchInstances(input *SearchInstancesInput) (*SearchInstancesOutput, error) {
	req, out := c.SearchInstancesRequest(input)
	return out, req.Send()
}

// SearchInstancesWithContext is the same as SearchInstances with the addition of
// the ability to pass a context and additional request options.
//
// See SearchInstances for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *BMQ) SearchInstancesWithContext(ctx volcengine.Context, input *SearchInstancesInput, opts ...request.Option) (*SearchInstancesOutput, error) {
	req, out := c.SearchInstancesRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type ItemForSearchInstancesOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	AuthEnabled *bool `type:"boolean" json:",omitempty"`

	BillingType *string `type:"string" json:",omitempty" enum:"EnumOfBillingTypeForSearchInstancesOutput"`

	CreateTime *string `type:"string" json:",omitempty"`

	Description *string `type:"string" json:",omitempty"`

	ExpirationTime *string `type:"string" json:",omitempty"`

	InstanceId *string `type:"string" json:",omitempty"`

	MessageRetention *int32 `type:"int32" json:",omitempty"`

	Name *string `type:"string" json:",omitempty"`

	RegionId *string `type:"string" json:",omitempty"`

	ResourceTags []*ResourceTagForSearchInstancesOutput `type:"list" json:",omitempty"`

	Specification *string `type:"string" json:",omitempty"`

	Status *string `type:"string" json:",omitempty" enum:"EnumOfStatusForSearchInstancesOutput"`

	Tags []*TagForSearchInstancesOutput `type:"list" json:",omitempty"`

	VpcId *string `type:"string" json:",omitempty"`

	ZoneIdList []*string `type:"list" json:",omitempty"`
}

// String returns the string representation
func (s ItemForSearchInstancesOutput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s ItemForSearchInstancesOutput) GoString() string {
	return s.String()
}

// SetAuthEnabled sets the AuthEnabled field's value.
func (s *ItemForSearchInstancesOutput) SetAuthEnabled(v bool) *ItemForSearchInstancesOutput {
	s.AuthEnabled = &v
	return s
}

// SetBillingType sets the BillingType field's value.
func (s *ItemForSearchInstancesOutput) SetBillingType(v string) *ItemForSearchInstancesOutput {
	s.BillingType = &v
	return s
}

// SetCreateTime sets the CreateTime field's value.
func (s *ItemForSearchInstancesOutput) SetCreateTime(v string) *ItemForSearchInstancesOutput {
	s.CreateTime = &v
	return s
}

// SetDescription sets the Description field's value.
func (s *ItemForSearchInstancesOutput) SetDescription(v string) *ItemForSearchInstancesOutput {
	s.Description = &v
	return s
}

// SetExpirationTime sets the ExpirationTime field's value.
func (s *ItemForSearchInstancesOutput) SetExpirationTime(v string) *ItemForSearchInstancesOutput {
	s.ExpirationTime = &v
	return s
}

// SetInstanceId sets the InstanceId field's value.
func (s *ItemForSearchInstancesOutput) SetInstanceId(v string) *ItemForSearchInstancesOutput {
	s.InstanceId = &v
	return s
}

// SetMessageRetention sets the MessageRetention field's value.
func (s *ItemForSearchInstancesOutput) SetMessageRetention(v int32) *ItemForSearchInstancesOutput {
	s.MessageRetention = &v
	return s
}

// SetName sets the Name field's value.
func (s *ItemForSearchInstancesOutput) SetName(v string) *ItemForSearchInstancesOutput {
	s.Name = &v
	return s
}

// SetRegionId sets the RegionId field's value.
func (s *ItemForSearchInstancesOutput) SetRegionId(v string) *ItemForSearchInstancesOutput {
	s.RegionId = &v
	return s
}

// SetResourceTags sets the ResourceTags field's value.
func (s *ItemForSearchInstancesOutput) SetResourceTags(v []*ResourceTagForSearchInstancesOutput) *ItemForSearchInstancesOutput {
	s.ResourceTags = v
	return s
}

// SetSpecification sets the Specification field's value.
func (s *ItemForSearchInstancesOutput) SetSpecification(v string) *ItemForSearchInstancesOutput {
	s.Specification = &v
	return s
}

// SetStatus sets the Status field's value.
func (s *ItemForSearchInstancesOutput) SetStatus(v string) *ItemForSearchInstancesOutput {
	s.Status = &v
	return s
}

// SetTags sets the Tags field's value.
func (s *ItemForSearchInstancesOutput) SetTags(v []*TagForSearchInstancesOutput) *ItemForSearchInstancesOutput {
	s.Tags = v
	return s
}

// SetVpcId sets the VpcId field's value.
func (s *ItemForSearchInstancesOutput) SetVpcId(v string) *ItemForSearchInstancesOutput {
	s.VpcId = &v
	return s
}

// SetZoneIdList sets the ZoneIdList field's value.
func (s *ItemForSearchInstancesOutput) SetZoneIdList(v []*string) *ItemForSearchInstancesOutput {
	s.ZoneIdList = v
	return s
}

type ResourceTagForSearchInstancesOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	TagKvs *TagKvsForSearchInstancesOutput `type:"structure" json:",omitempty"`

	Type *string `type:"string" json:",omitempty" enum:"EnumOfTypeForSearchInstancesOutput"`
}

// String returns the string representation
func (s ResourceTagForSearchInstancesOutput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s ResourceTagForSearchInstancesOutput) GoString() string {
	return s.String()
}

// SetTagKvs sets the TagKvs field's value.
func (s *ResourceTagForSearchInstancesOutput) SetTagKvs(v *TagKvsForSearchInstancesOutput) *ResourceTagForSearchInstancesOutput {
	s.TagKvs = v
	return s
}

// SetType sets the Type field's value.
func (s *ResourceTagForSearchInstancesOutput) SetType(v string) *ResourceTagForSearchInstancesOutput {
	s.Type = &v
	return s
}

type SearchInstancesInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	CreateTimeOrder *string `type:"string" json:",omitempty"`

	// PageNumber is a required field
	PageNumber *int32 `type:"int32" json:",omitempty" required:"true"`

	// PageSize is a required field
	PageSize *int32 `type:"int32" json:",omitempty" required:"true"`

	ProjectName *string `type:"string" json:",omitempty"`

	SearchKey *string `type:"string" json:",omitempty"`

	Status []*string `type:"list" json:",omitempty"`

	TagFilters []*TagFilterForSearchInstancesInput `type:"list" json:",omitempty"`
}

// String returns the string representation
func (s SearchInstancesInput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s SearchInstancesInput) GoString() string {
	return s.String()
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *SearchInstancesInput) Validate() error {
	invalidParams := request.ErrInvalidParams{Context: "SearchInstancesInput"}
	if s.PageNumber == nil {
		invalidParams.Add(request.NewErrParamRequired("PageNumber"))
	}
	if s.PageSize == nil {
		invalidParams.Add(request.NewErrParamRequired("PageSize"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

// SetCreateTimeOrder sets the CreateTimeOrder field's value.
func (s *SearchInstancesInput) SetCreateTimeOrder(v string) *SearchInstancesInput {
	s.CreateTimeOrder = &v
	return s
}

// SetPageNumber sets the PageNumber field's value.
func (s *SearchInstancesInput) SetPageNumber(v int32) *SearchInstancesInput {
	s.PageNumber = &v
	return s
}

// SetPageSize sets the PageSize field's value.
func (s *SearchInstancesInput) SetPageSize(v int32) *SearchInstancesInput {
	s.PageSize = &v
	return s
}

// SetProjectName sets the ProjectName field's value.
func (s *SearchInstancesInput) SetProjectName(v string) *SearchInstancesInput {
	s.ProjectName = &v
	return s
}

// SetSearchKey sets the SearchKey field's value.
func (s *SearchInstancesInput) SetSearchKey(v string) *SearchInstancesInput {
	s.SearchKey = &v
	return s
}

// SetStatus sets the Status field's value.
func (s *SearchInstancesInput) SetStatus(v []*string) *SearchInstancesInput {
	s.Status = v
	return s
}

// SetTagFilters sets the TagFilters field's value.
func (s *SearchInstancesInput) SetTagFilters(v []*TagFilterForSearchInstancesInput) *SearchInstancesInput {
	s.TagFilters = v
	return s
}

type SearchInstancesOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata

	Items []*ItemForSearchInstancesOutput `type:"list" json:",omitempty"`

	PageCount *int32 `type:"int32" json:",omitempty"`

	PageNumber *int32 `type:"int32" json:",omitempty"`

	PageSize *int32 `type:"int32" json:",omitempty"`

	TotalCount *int64 `type:"int64" json:",omitempty"`
}

// String returns the string representation
func (s SearchInstancesOutput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s SearchInstancesOutput) GoString() string {
	return s.String()
}

// SetItems sets the Items field's value.
func (s *SearchInstancesOutput) SetItems(v []*ItemForSearchInstancesOutput) *SearchInstancesOutput {
	s.Items = v
	return s
}

// SetPageCount sets the PageCount field's value.
func (s *SearchInstancesOutput) SetPageCount(v int32) *SearchInstancesOutput {
	s.PageCount = &v
	return s
}

// SetPageNumber sets the PageNumber field's value.
func (s *SearchInstancesOutput) SetPageNumber(v int32) *SearchInstancesOutput {
	s.PageNumber = &v
	return s
}

// SetPageSize sets the PageSize field's value.
func (s *SearchInstancesOutput) SetPageSize(v int32) *SearchInstancesOutput {
	s.PageSize = &v
	return s
}

// SetTotalCount sets the TotalCount field's value.
func (s *SearchInstancesOutput) SetTotalCount(v int64) *SearchInstancesOutput {
	s.TotalCount = &v
	return s
}

type TagFilterForSearchInstancesInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Key *string `type:"string" json:",omitempty"`

	Values []*string `type:"list" json:",omitempty"`
}

// String returns the string representation
func (s TagFilterForSearchInstancesInput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s TagFilterForSearchInstancesInput) GoString() string {
	return s.String()
}

// SetKey sets the Key field's value.
func (s *TagFilterForSearchInstancesInput) SetKey(v string) *TagFilterForSearchInstancesInput {
	s.Key = &v
	return s
}

// SetValues sets the Values field's value.
func (s *TagFilterForSearchInstancesInput) SetValues(v []*string) *TagFilterForSearchInstancesInput {
	s.Values = v
	return s
}

type TagForSearchInstancesOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Key *string `type:"string" json:",omitempty"`

	Type *string `type:"string" json:",omitempty" enum:"EnumOfTypeForSearchInstancesOutput"`

	Value *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s TagForSearchInstancesOutput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s TagForSearchInstancesOutput) GoString() string {
	return s.String()
}

// SetKey sets the Key field's value.
func (s *TagForSearchInstancesOutput) SetKey(v string) *TagForSearchInstancesOutput {
	s.Key = &v
	return s
}

// SetType sets the Type field's value.
func (s *TagForSearchInstancesOutput) SetType(v string) *TagForSearchInstancesOutput {
	s.Type = &v
	return s
}

// SetValue sets the Value field's value.
func (s *TagForSearchInstancesOutput) SetValue(v string) *TagForSearchInstancesOutput {
	s.Value = &v
	return s
}

type TagKvsForSearchInstancesOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`
}

// String returns the string representation
func (s TagKvsForSearchInstancesOutput) String() string {
	return volcengineutil.Prettify(s)
}

// GoString returns the string representation
func (s TagKvsForSearchInstancesOutput) GoString() string {
	return s.String()
}

const (
	// EnumOfBillingTypeForSearchInstancesOutputMix is a EnumOfBillingTypeForSearchInstancesOutput enum value
	EnumOfBillingTypeForSearchInstancesOutputMix = "MIX"

	// EnumOfBillingTypeForSearchInstancesOutputPost is a EnumOfBillingTypeForSearchInstancesOutput enum value
	EnumOfBillingTypeForSearchInstancesOutputPost = "POST"

	// EnumOfBillingTypeForSearchInstancesOutputPre is a EnumOfBillingTypeForSearchInstancesOutput enum value
	EnumOfBillingTypeForSearchInstancesOutputPre = "PRE"
)

const (
	// EnumOfStatusForSearchInstancesOutputInitializing is a EnumOfStatusForSearchInstancesOutput enum value
	EnumOfStatusForSearchInstancesOutputInitializing = "INITIALIZING"

	// EnumOfStatusForSearchInstancesOutputInitializationFailed is a EnumOfStatusForSearchInstancesOutput enum value
	EnumOfStatusForSearchInstancesOutputInitializationFailed = "INITIALIZATION_FAILED"

	// EnumOfStatusForSearchInstancesOutputRunning is a EnumOfStatusForSearchInstancesOutput enum value
	EnumOfStatusForSearchInstancesOutputRunning = "RUNNING"

	// EnumOfStatusForSearchInstancesOutputUpdating is a EnumOfStatusForSearchInstancesOutput enum value
	EnumOfStatusForSearchInstancesOutputUpdating = "UPDATING"

	// EnumOfStatusForSearchInstancesOutputScaleUp is a EnumOfStatusForSearchInstancesOutput enum value
	EnumOfStatusForSearchInstancesOutputScaleUp = "SCALE_UP"

	// EnumOfStatusForSearchInstancesOutputScaleDown is a EnumOfStatusForSearchInstancesOutput enum value
	EnumOfStatusForSearchInstancesOutputScaleDown = "SCALE_DOWN"

	// EnumOfStatusForSearchInstancesOutputModifying is a EnumOfStatusForSearchInstancesOutput enum value
	EnumOfStatusForSearchInstancesOutputModifying = "MODIFYING"

	// EnumOfStatusForSearchInstancesOutputModifyFailed is a EnumOfStatusForSearchInstancesOutput enum value
	EnumOfStatusForSearchInstancesOutputModifyFailed = "MODIFY_FAILED"

	// EnumOfStatusForSearchInstancesOutputReleasing is a EnumOfStatusForSearchInstancesOutput enum value
	EnumOfStatusForSearchInstancesOutputReleasing = "RELEASING"

	// EnumOfStatusForSearchInstancesOutputStopping is a EnumOfStatusForSearchInstancesOutput enum value
	EnumOfStatusForSearchInstancesOutputStopping = "STOPPING"

	// EnumOfStatusForSearchInstancesOutputStopped is a EnumOfStatusForSearchInstancesOutput enum value
	EnumOfStatusForSearchInstancesOutputStopped = "STOPPED"

	// EnumOfStatusForSearchInstancesOutputRecovering is a EnumOfStatusForSearchInstancesOutput enum value
	EnumOfStatusForSearchInstancesOutputRecovering = "RECOVERING"

	// EnumOfStatusForSearchInstancesOutputException is a EnumOfStatusForSearchInstancesOutput enum value
	EnumOfStatusForSearchInstancesOutputException = "EXCEPTION"

	// EnumOfStatusForSearchInstancesOutputExpandingCapacity is a EnumOfStatusForSearchInstancesOutput enum value
	EnumOfStatusForSearchInstancesOutputExpandingCapacity = "EXPANDING_CAPACITY"

	// EnumOfStatusForSearchInstancesOutputCapacityExpaxionFailed is a EnumOfStatusForSearchInstancesOutput enum value
	EnumOfStatusForSearchInstancesOutputCapacityExpaxionFailed = "CAPACITY_EXPAXION_FAILED"

	// EnumOfStatusForSearchInstancesOutputCancelExpandingCapacity is a EnumOfStatusForSearchInstancesOutput enum value
	EnumOfStatusForSearchInstancesOutputCancelExpandingCapacity = "CANCEL_EXPANDING_CAPACITY"

	// EnumOfStatusForSearchInstancesOutputExpired is a EnumOfStatusForSearchInstancesOutput enum value
	EnumOfStatusForSearchInstancesOutputExpired = "EXPIRED"

	// EnumOfStatusForSearchInstancesOutputStarting is a EnumOfStatusForSearchInstancesOutput enum value
	EnumOfStatusForSearchInstancesOutputStarting = "STARTING"

	// EnumOfStatusForSearchInstancesOutputRestarting is a EnumOfStatusForSearchInstancesOutput enum value
	EnumOfStatusForSearchInstancesOutputRestarting = "RESTARTING"

	// EnumOfStatusForSearchInstancesOutputUnpaid is a EnumOfStatusForSearchInstancesOutput enum value
	EnumOfStatusForSearchInstancesOutputUnpaid = "UNPAID"

	// EnumOfStatusForSearchInstancesOutputPartialException is a EnumOfStatusForSearchInstancesOutput enum value
	EnumOfStatusForSearchInstancesOutputPartialException = "PARTIAL_EXCEPTION"

	// EnumOfStatusForSearchInstancesOutputShutdown is a EnumOfStatusForSearchInstancesOutput enum value
	EnumOfStatusForSearchInstancesOutputShutdown = "SHUTDOWN"
)

const (
	// EnumOfTypeForSearchInstancesOutputSystem is a EnumOfTypeForSearchInstancesOutput enum value
	EnumOfTypeForSearchInstancesOutputSystem = "SYSTEM"

	// EnumOfTypeForSearchInstancesOutputCustom is a EnumOfTypeForSearchInstancesOutput enum value
	EnumOfTypeForSearchInstancesOutputCustom = "CUSTOM"
)
